/* ES6/DOM4 polyfill for IE < 8 | @version 0.7 final | MIT License | github.com/termi */
void function() {
var f=void 0,g=!0,j=null,l=!1;function aa(){return function(){}}var n=window;function p(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&!Object.prototype.hasOwnProperty.call(a,c)&&(a[c]=b[c]);return a}
function ba(a){if(!("__isFixed"in a)){var b="button"in a&&a.button;a.__isFixed=g;if("click"===a.type||"dblclick"===a.type)a.detail===f&&(a.detail="click"===a.type?1:2),!a.button&&ba.b!==f&&(b=ba.b);p(a,u);a.defaultPrevented||(a.defaultPrevented=l);a.target||(a.target=a.srcElement||document);a.relatedTarget===f&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==j&&(a.pageX=a.clientX+ca()-(v.clientLeft||0),a.pageY=a.clientY+da()-(v.clientTop||
0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new ea);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);"currentTarget"in a||(a.currentTarget=this);a.keyCode||(a.keyCode=a.charCode||a.which);!a.attrName&&a.propertyName&&(a.attrName=fa.call(a.propertyName,".")[0]);return a}}
function ia(a){if(ba!==f){var b=this._,c,d,e,m;if(!b.__stop_events__){c=[];d=[];m="_e_8vj"+(ja?"-":"");if(!b||!b[m])if("__dom0__"in a)b||(b={}),b[m]||(b[m]={});else return;a||(a=window.event);if("__custom_event"in a)e=a;else if(!(e=a.__customEvent__))a.bubbles==f&&(a.bubbles=g),a.cancelable==f&&(a.cancelable=g),e=a.__customEvent__=new w(a),e.initEvent(a.type,a.bubbles,a.cancelable),ba.call(this,e),e.g=g,e.__custom_event=f;e.ietl9_event=a;a.currentTarget=this;b=b[m][e.type];"__dom0__"in a&&((b||(b=
[]))[0]=a.__dom0__);if(b){for(var k in b)if(y(b,k)){m=b[k];var q;"object"===typeof m&&(q=m,m=m.handleEvent);try{if(m&&(e.result=C.call(m,q||this,e))===l)e.preventDefault(),e.stopPropagation()}catch(r){c.push(r),d.push(r.message),console&&console.error(r)}if(e.__stopNow)break}b[0]=f;delete b[0];a.returnValue=e.returnValue;a.cancelBubble=e.cancelBubble;1==c.length?ka(c[0]):1<c.length&&(d=Error("Multiple errors thrown : "+e.type+" :  : "+d.join("|")),d.errors=c,ka(d))}this===document&&(!e.cancelBubble&&
3===e.eventPhase)&&(ia.call(this.defaultView,e),a.cancelBubble=g)}}}function la(){}function ma(a){var b=this.__orig__createElement__(a);if(na.test(a))return b;~oa.indexOf("|"+a+"|")||(ta.push(a),oa+=a+"|",(D.__orig__createElement__||D.createElement)(a));return D.appendChild(b)}function ua(a){var b=-1;if(a.createElement){for(;++b<ta.length;)a.createElement(ta[b]);a.createElement!==ma&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=ma)}return a}
function va(a,b,c,d,e,m){var k=a.match(xa);a=c||[];var q=!!e,r=q&&(b={})||(!b?document:"length"in b?b[0]:b),B,G=0,h,t,J=ya[k[1]||""]||0,ga=2<J,K=k[2],pa=!!K,qa=k[3],wa=!!qa,ra=k[4],ha=!!ra,Fa="*"===K,A,Ya,s,F,R,L,x,U,Za,V,sa,H,z,Ga,$a,ab;pa&&(K=Fa?f:K.replace("|",":").toUpperCase());ha&&(ra=ra.replace(za," "),Za=RegExp(ra.replace(Aa,Ba)));if(V=k[5]){V=fa.call(V,"][");for(A=-1;F=V[++A];)if(F=V[A]=F.match(Ca),F[2]=Da[F[2]],(z=F[3])&&" i"==z.substr(-2))z.substr(0,z.length-2),F[4]=g}if(k=k[6])k=k.match(Ea),
L=Ha[k[1]],2>L&&k[2]&&(R=/\D/.test(k[2])?"even"===k[2]?[j,2]:"odd"===k[2]?[j,2,"%",1]:k[2].match(Ia):[j,0,"%",k[2]],Ga=L?"nodeIndexLast":"nodeIndex",$a=L?"lastChild":"firstChild",ab=L?"previousSibling":"nextSibling");q&&(J=0);if(1==J)if(wa){e=document.getElementsByName(qa);sa=[];for(A=-1;h=e[++A];)h.id==qa&&sa.push(h);e=wa=pa=j}else K||(K="*",Fa=!ha),pa=l;q=(!("length"in b)||1===b.length)&&!d&&!V&&!k&&!pa&&!ha&&!wa;do{switch(J){case 0:h=e[0];break;case 1:if(qa)if(e=[],sa.length)for(A=-1;h=sa[++A];){if(r===
document||r.contains(h))e.push(h),sa.splice(A--,1)}else return a;else"BODY"===K&&9===r.nodeType?(e=[r.body],ha=!!ra,q=q&&!ha):e=r.getElementsByTagName(K);h=e[0];break;case 2:e=r.children;h=e[0];break;case 3:B=b[G+1];case 4:if(!(h=Ja(r)))continue}if(q)return e;r=0;if(h){do if((!Fa||1===h.nodeType)&&!(d&&(Ya=h.sourceIndex)in c)){if(s=!(pa&&(t=h.nodeName.toUpperCase())!==K||wa&&h.id!==qa||ha&&(!h.className||!Za.test(h.className)))){if(V)for(A=-1;s&&(F=V[++A]);)if(H=F[2],z=h,x=F[1],x=x.toLowerCase(),
x=E[x]!==f?z[E[x]]:Ka[x]!==f?z.__getAttribute__(x,2):La[x]!==f?z.__getAttribute__(x)?x:j:(z=z.getAttributeNode(x))&&z.value,x===j){if(!(s=8==H))s=l}else switch(F[4]&&(x=x.toUpperCase()),U=F[3],H){case 1:s=!!x||""===x;break;case 2:s=x===U;break;case 3:case 8:s=RegExp("(^| +)"+U+"($| +)").test(x);8==H&&(s=!s);break;case 4:case 5:case 6:z=x.indexOf(U);s=6===H?~z:5===H?z==x.length-U.length:!z;break;case 7:s=x===U||!!~x.indexOf(U+"-");break;case 9:s=!!~(" "+x.replace(Ma," ")+" ").indexOf(" "+U+" ")}if(s&&
k)switch(L){case 0:case 1:if(!R[1]&&!R[3])break;A=h[Ga]||0;H=R[3]?("%"===R[2]?-1:1)*R[3]:0;z=R[1];if(A)s=!z?!(A+H):!((A+H)%z);else{s=l;t=h.parentNode[$a];do if(1==t.nodeType&&(t[Ga]=++A)&&h===t&&(!z?!(A+H):!((A+H)%z)))s=g;while(!s&&(t=t[ab]))}break;case 2:case 3:for(t=h;(t=t.previousSibling)&&1!==t.nodeType;);s=!t;if(!s||3==L)break;case 4:s=!Ja(h);break;case 5:s="HTML"==(t||h.nodeName.toUpperCase());break;case 6:s=!h.firstChild;break;case 7:s=!!h.checked;break;case 8:s=h.lang==R||v.lang==R;break;
case 9:case 10:s="disabled"in h&&"form"in h&&(10==L?h.disabled===g&&"hidden"!==h.type:h.disabled===l);break;case 11:s=h.parentNode.selectedIndex&&!!h.selected;break;case 12:s=!!~(h.textContent||h.data||h.innerText||h.nodeValue||h.value||"").indexOf(k[2]);break;case 13:case 14:s=Na.call(h,k[2]);13==L&&(s=!s);break;case 15:case 16:t||(t=h.nodeName.toUpperCase()),s=("INPUT"==t||"TEXTAREA"==t||C.call(h,h.__getAttribute__||h.getAttribute,"contenteditable")!==j)&&!h.r,16==L&&(s=!s)}}if(s){if(m)return[h];
d?a[Ya]=h:a.push(h)}t=f}while(h=ga?4===J?f:h===B?f:Ja(h):e[++r])}h=f}while(r=b[++G]);return a}
function Oa(a,b,c){c||(c=this);a=Pa.call(a.replace(Qa,"$1"));var d=[],e,m,k,q=g,r=l,B,G=a.replace(Ra,"@=").replace(Sa,"-child\\($1%$2\\)").match(Ta);for(e=c;a=G.shift();){m=G[0];k=!m||","===m.charAt(0);if(!r)if(q&&"nodeType"in c&&9===c.nodeType&&"BODY"===a.toUpperCase())e=[c.body],k&&(d=e);else if(q&&":root"===a)e=[v],k&&(d=e);else if(e&&(!(c=e)||0===e.length))e=j,r=g;else{if(q=!(!k||!B&&!(m||1<c.length)))B=g;e=va(a,c,k?d:[],q,j,b&&k)}if(q=k)!d.length&&e&&(B=l,d=Ua(e)),e=j,c=this,r=l;if(!m||","===
m)break}return B?Ua(d):d}
function Na(a){if(!a)return l;if("*"===a||this===v&&":root"===a||this===document.body&&"BODY"===a.toUpperCase())return g;var b,c,d=l,e;a=Pa.call(a);if(b=a.match(Va))switch(a.charAt(0)){case "#":return this.id===a.slice(1);default:return(d=!(c=b[2])||this.className&&RegExp(c.replace(za," ").replace(Aa,Ba)).test(this.className))&&!(c=b[1])||this.tagName&&this.tagName.toUpperCase()===c.toUpperCase()}else{if(Wa.test(a)){c=Oa.call(this.ownerDocument,a);for(e in c)if(y(c,e)&&(d=c[e]===this))return g;return l}c=
va(a,j,l,j,this,g);return c[0]===this}}function Xa(){document.removeEventListener("DOMContentLoaded",Xa);bb&&(document.readyState="interactive");I&&I()}function cb(){n.detachEvent("onload",cb);bb&&(document.readyState="complete");I&&I()}var db=window.eval&&window.eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||j;
if(9>db){n.Element||((n.Element=window.ActiveXObject).prototype.ie=g);n.HTMLElement||(n.HTMLElement=n.Element);n.Node||(n.Node=n.Element);var eb;n.DocumentFragment||(n.DocumentFragment=n.Document||n.HTMLDocument||(eb=aa(),eb.prototype={},eb));n.Document||(n.Document=n.DocumentFragment);n._={ielt9shims:[],orig_:n._};var M=n._.ielt9shims,fb=document.createDocumentFragment,gb=document.createElement,hb=document.createTextNode,v=document.documentElement,ka=function(a){throw a instanceof Error?a:Error(a);
},ib=function(a){var b=Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},jb=function(a,b){for(var c in b)if(y(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(d){}},Pa=String.prototype.trim||function(){for(var a=this.replace(kb,""),b=a.length;lb.test(a.charAt(--b)););return a.slice(0,b+1)},fa=String.prototype.split,mb=String.prototype.substr,nb=Array.prototype.slice,ob=Function.prototype.apply,C=Function.prototype.call,N=Function.prototype.bind||function(a,
b){var c=this,d=nb.call(arguments,1);return function(){return ob.call(c,a,d.concat(nb.call(arguments)))}},O,y=N.call(Function.prototype.call,Object.prototype.hasOwnProperty),P=document.createElement("p"),Q=n.Node.prototype,S=n.Element.prototype,pb=P.contains||Q.contains,ea=Date,qb=/^\<([\w\:\-]*)[\>\ ]/i,kb=/^\s+/,lb=/\s/,rb,T,W,sb="every filter forEach indexOf join lastIndexOf map reduce reduceRight reverse slice some toString".split(" "),tb,ub=/alpha\(opacity=([^\)]+)\)/,vb=function(){var a=(this.filter||
"").match(ub);return a?parseInt(a[1])/100+"":""},wb={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))",
"i"))||[])[2]||""},item:aa()},E={"for":"htmlFor","class":"className",value:"defaultValue"},Ka={action:j,cite:j,codebase:j,data:j,href:j,longdesc:j,lowsrc:j,src:j,usemap:j},xb={id:g,value:g,checked:g,disabled:g,ismap:g,multiple:g,readonly:g,selected:g},La={checked:j,disabled:j,ismap:j,multiple:j,readonly:j,selected:j},w,yb,u,zb=1,Ab=aa(),ja=l,Bb,oa="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|nav|output|progress|section|source|summary|time|video",
ta=oa.split("|"),na=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,Cb,D,Db,Eb,ca,da;T=document.createElement("iframe");T.style.display="none";(document.body||v).appendChild(T);T.contentWindow.document.write("<script>parent._.NodeList=Array;parent._.EMP=Object.prototype\x3c/script>");tb=n._.NodeList;delete n._.NodeList;O=n._.EMP;delete n._.EMP;
delete O.constructor;delete O.hasOwnProperty;delete O.propertyIsEnumerable;delete O.isPrototypeOf;delete O.toLocaleString;delete O.toString;delete O.valueOf;O.__proto__=j;M.push(function(){var a=Object.create;Object.create=function(b){b===j&&(arguments[0]=O);a.apply(this,arguments)}});"CSS1Compat"===document.compatMode?(ca=function(){return v.scrollLeft},da=function(){return v.scrollTop}):(ca=function(){return document.body.scrollTop},da=function(){return document.body.scrollLeft});document.head||
(document.head=document.getElementsByTagName("head")[0]);"defaultView"in document||(document.defaultView=document.parentWindow);T=l;try{T=isNaN.apply(j,{})}catch(Fb){}T||(Function.prototype.apply=function(a,b){return!b?ob.call(this,a):"object"!==typeof b||b instanceof Array||!("length"in b)?ob.call(this,a,b):ob.call(this,a,Array.from(b))});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return mb.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if("te".split(/(s)*/)[1]!=f||3!="1_1".split(/(_)/).length)rb=
/()??/.exec("")[1]===f,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===f&&0===b?[]:fa.call(c,a,b);var d=[],e=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.extended?"x":"")+(a.sticky?"y":""),m=0,k,q,r;a=RegExp(a.source,e+"g");c+="";rb||(k=RegExp("^"+a.source+"$(?!\\s)",e));b=b===f?4294967295:b>>>0;if(!b)return[];for(;q=a.exec(c);){e=q.index+q[0].length;if(e>m&&(d.push(c.slice(m,q.index)),!rb&&1<q.length&&q[0].replace(k,function(){for(var a=1,b=arguments.length-
2;a<b;a++)arguments[a]===f&&(q[a]=f)}),1<q.length&&q.index<c.length&&d.push.apply(d,q.slice(1)),r=q[0].length,m=e,d.length>=b))break;a.lastIndex===q.index&&a.lastIndex++}m===c.length?(r||!a.test(""))&&d.push(""):d.push(c.slice(m));return d.length>b?d.slice(0,b):d};n.DOMException||(T=(n.DOMException=aa()).prototype=Error(),T.INDEX_SIZE_ERR=1,T.HIERARCHY_REQUEST_ERR=3,T.WRONG_DOCUMENT_ERR=4,T.INVALID_CHARACTER_ERR=5,T.NO_MODIFICATION_ALLOWED_ERR=7,T.NOT_FOUND_ERR=8,T.NOT_SUPPORTED_ERR=9,T.INVALID_STATE_ERR=
11,T.SYNTAX_ERR=12,T.INVALID_MODIFICATION_ERR=13,T.NAMESPACE_ERR=14,T.INVALID_ACCESS_ERR=15);"pageXOffset"in n||M.push(function(){Object.defineProperty(n,"pageXOffset",{get:ca});Object.defineProperty(n,"pageYOffset",{get:da})});W=n.Event=function(){ka("")};yb={initEvent:function(a,b,c){(a==f||b==f||c==f)&&ka("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=c;this.g=l;this.target=j;this.timeStamp||(this.timeStamp=+new ea)},initCustomEvent:function(a,b,c,d){yb.initEvent.call(this,a,
b,c);this.detail=d},initUIEvent:function(a,b,c,d,e){yb.initCustomEvent.call(this,a,b,c,e);this.view=d},initMouseEvent:function(a,b,c,d,e,m,k,q,r,B,G,h,t,J,ga){yb.initUIEvent.call(this,a,b,c,d,e);this.screenX=m;this.screenY=k;this.clientX=q;this.clientY=r;this.ctrlKey=B;this.altKey=G;this.shiftKey=h;this.metaKey=t;this.button=J;this.relatedTarget=ga}};u=W.prototype={constructor:W,preventDefault:function(){this.cancelable!==l&&(w.a.call(this).returnValue=this.returnValue=l,w.d.call(this),this.defaultPrevented=
g)},stopPropagation:function(){w.a.call(this).cancelBubble=this.cancelBubble=g;w.d.call(this)}};u.stopImmediatePropagation=function(){this.__stopNow=g;this.stopPropagation()};u.defaultPrevented=l;for(T in yb)y(yb,T)&&(u[T]=function(){yb[arguments.callee.name].apply(this,arguments);jb(this.ietl9_event,this)},u[T].name=T);w=function(a){this.ietl9_event=a;a.returnValue=g;jb(this,a)};w.a=function(){var a=this.ietl9_event;a===f?ka("WRONG_THIS_ERR"):a===j&&(a=w.a.f);return a};w.a.f={};w.d=function(){this.ietl9_event&&
(this.ietl9_event=j)};W=aa();W.prototype=u;W=new W;W.constructor=w;w.prototype=W;document.addEventListener||(Q.addEventListener=v.addEventListener=n.addEventListener=document.addEventListener=function(a,b,c){if("function"==typeof b||"object"===typeof b&&b.handleEvent){var d=this,e=d._,m=l;d==n&&(!("_"in document)||!("_e_8vj"in document._)||!(a in document._._e_8vj))&&document.addEventListener(a,Ab,c);e||(e=d._={});switch(a){case "DOMContentLoaded":if("complete"==document.readyState)return;d===n&&
(d=document);m=g;if(!Bb){Bb=g;var k=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(k,50);return}ia.call(d,{type:a,isTrusted:g,__custom_event:f})};if("createEventObject"in document&&"doScroll"in document.documentElement)try{n.frameElement||k()}catch(q){}}break;case "load":"tagName"in d&&"SCRIPT"===d.tagName.toUpperCase()&&(m=g,d.onreadystatechange=function(){"loaded"===d.readyState&&(d.onreadystatechange=j,d.attachEvent("onreadystatechange",N.call(ia,d,{type:a})))},a=
"readystatechange");break;case "DOMMouseScroll":a="mousewheel"}d.setInterval&&(d!=n&&!d.frameElement)&&(d=n);b.uuid||(b.uuid=++zb);if(!(c=e._h_9e2))c=e._h_9e2=N.call(ia,d);e._e_8vj||(e._e_8vj={});e._e_8vj[a]||(e._e_8vj[a]={},m||d.attachEvent("on"+a,c));e._e_8vj[a][b.uuid]=b}},Q.addEventListener.__shim__=g,Q.removeEventListener=v.removeEventListener=n.removeEventListener=document.removeEventListener=function(a,b){var c=this._,d,e;if(!("function"!=typeof b&&!("object"===typeof b&&b.handleEvent)||!b.uuid||
!c))if(d=c._h_9e2){e=c._e_8vj&&c._e_8vj[a];delete e[b.uuid];for(any in e)if(y(e,any))return;this.detachEvent("on"+a,d);delete c._e_8vj[a];for(any in c._e_8vj)if(y(c._e_8vj,any))return;delete c._e_8vj}},Q.removeEventListener.__shim__=g,document.attachEvent("onmousedown",function(){ba.b=event.button}),document.attachEvent("onclick",function(){ba.b=f}));document.dispatchEvent||(Q.dispatchEvent=v.dispatchEvent=n.dispatchEvent=document.dispatchEvent=function(a){if(!a.type)return g;a.returnValue||(a.returnValue=
g);a.cancelBubble&&(a.cancelBubble=l);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===n||-2146827850===b.number&&!(a.bubbles=l)){a.__custom_event=g;for(var c=a.target=this,d="on"+a.type;!a.cancelBubble&&c;)(d in c&&"function"==typeof c[d]&&(a.__dom0__=c[d])||"_"in c&&"_e_8vj"in c._)&&ia.call(c,a),c=a.bubbles?c===document?document.defaultView:c.parentNode:j,"__dom0__"in a&&(a.__dom0__=f);return!a.cancelBubble}ka(b)}},Q.dispatchEvent.__shim__=g);
document.createEvent||(document.createEvent=function(){return new w(document.createEventObject())});M.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),d,r,B,G,h,t,J,ga;if(!("INPUT"!=c&&"TEXTAREA"!=c)){"unknown"!=typeof document.activeElement&&(t=document.activeElement);b=document.selection;this._&&(J=this._.__stop_events__,this._.__stop_events__=g);t&&t._&&(ga=t._.__stop_events__,t._.__stop_events__=g);try{this.focus(),d=b.createRange(),r=d.duplicate(),"TEXTAREA"==c?(B=this.value,
d=r,a?(d.moveEnd("character",B.length),h=""==d.text?B.length:B.lastIndexOf(d.text)):(d.moveStart("character",-B.length),h=d.text.length)):(r.moveToElementText(this),r.setEndPoint("EndToEnd",d),G=r.text.length-d.text.length,h=a?G:G+d.text.length),t&&t.focus&&t.focus()}catch(K){h=f}this._&&!J&&delete this._.__stop_events__;t&&(t._&&!ga)&&delete t._.__stop_events__;return h}}function b(a,b){if(a!=f){b==f&&(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(g),
c.moveStart("character",a),c.moveEnd("character",b-a),c.select())}}var c=n.HTMLTextAreaElement&&n.HTMLTextAreaElement.prototype,d={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,g)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},set:function(c){b.call(this,a.call(this,g),c);return c}}};Object.defineProperties(n.HTMLInputElement&&n.HTMLInputElement.prototype||S,d);c&&Object.defineProperties(c,d)});la.prototype=
[];T=new la;T.push(1);T.length?(n.NodeList=la,tb=j):la=n.NodeList=tb;la.prototype.item=function(a){return this[a]};if(document.querySelectorAll){var Gb=document.querySelectorAll("#z").constructor.prototype;if(Gb&&Gb!==Array.prototype)for(var Hb in sb)y(Hb,sb)&&(Gb[Hb]||(Gb[Hb]=function(){return ob.call(Array.prototype[Hb],Array.from(this),arguments)}))}document.doctype===j&&7<db&&M.push(function(){var a=document.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});Object.defineProperty(document,
"doctype",{configurable:g,enumerable:l,get:function(){return a}})});Q.contains||(Q.contains=pb);C.call(hb,document,"").contains||(n.Text&&n.Text.prototype?M.push(N.call(p,j,Text.prototype,Q)):document.createTextNode=function(a){a=C.call(hb,this,a);a.contains=Q.contains;return a});!C.call(fb,document).contains&&(n.HTMLDocument&&n.HTMLDocument.prototype)&&M.push(N.call(p,j,n.HTMLDocument.prototype,Q));"children"in P||M.push(function(){Object.defineProperty(S,"children",{get:function(){for(var a=[],
b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});M.push(function(){function a(a,c){var d;try{a:{var e=a;"element"in e&&("defaults"in e&&"document"in e)&&(e=e.element);var m=e.getBoundingClientRect(),k,q,r;if((r=e.ownerDocument)!==document){if(k=r&&r.body,q=r&&r.documentElement,!k||!q){d=c?m.left:m.top;break a}}else k=document.body,q=v;d=c?m.left+ca()-(q.clientLeft||k.clientLeft||0):m.top+da()-(q.clientTop||k.clientTop||0)}}catch(B){d=a;e=0;for(m=c?"offsetLeft":"offsetTop";d;)e+=
parseInt(d[m],10),d=d.offsetParent;d=e}return d}Object.defineProperties(S,{offsetLeft:{get:function(){return a(this,g)}},offsetTop:{get:function(){return a(this)}}})});P.childElementCount==f&&M.push(function(){Object.defineProperties(S,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=this;(a=
a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});document.ELEMENT_NODE||(T={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},p(document,T),p(Q,T),p(n.Node,T));"textContent"in P||M.push(function(){Object.defineProperty(Q,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in this&&
this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in P||(document.isEqualNode=v.isEqualNode=Q.isEqualNode=function(a){var b,c;if(a===j||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return l;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return l;
b=0;for(c=this.attributes.length;b<c;b++){var d=this.attributes[length],e=a.getAttributeNS(d.namespaceURI,d.localName);if(e===j||e.value!==d.value)return l}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return l;b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===l)return l;return g});document.importNode||(document.importNode=function(a,b){switch(a.nodeType){case 1:var c=
document.createElement(a.nodeName),d=a.attributes,e,m,k;if(d&&0<d.length){m=0;for(k=d.length;m<k;)d=a.attributes[m++],c.setAttribute(d.nodeName,a.getAttribute(d.nodeName))}if(b&&(e=a.childNodes)&&0<e.length){m=0;for(k=e.length;m<k;)c.appendChild(document.importNode(e[m++],b))}return c;case 3:case 4:case 8:return document.createTextNode(a.nodeValue)}ib("NOT_SUPPORTED_ERR");return j},document.importNode.shim=g);T="compareDocumentPosition";if(!(T in document)){var X,Y=X||"DOCUMENT_POSITION_";v[T]=document[T]=
Q[T]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0};X="DISCONNECTED";v[Y+X]=document[Y+X]=Q[Y+X]=1;X="PRECEDING";v[Y+X]=document[Y+X]=Q[Y+X]=2;X="FOLLOWING";v[Y+X]=document[Y+X]=Q[Y+X]=4;X="CONTAINS";v[Y+X]=document[Y+X]=Q[Y+X]=8;X="CONTAINED_BY";v[Y+X]=document[Y+X]=Q[Y+X]=16}n.getComputedStyle||(n.getComputedStyle=function(a){var b=
a.currentStyle||a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=wb.getPropertyValue.bind(a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=function(){ib("NO_MODIFICATION_ALLOWED_ERR")},a.runtimeStyle.getPropertyPriority=function(){return""},a.runtimeStyle.item=wb.item);var c,d;(d=n.CSSStyleDeclaration)&&(d=d.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(d,"float"))&&delete d["float"],Object.defineProperty(a.runtimeStyle,
"float",{value:{valueOf:N.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}}),c&&Object.defineProperty(d,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(d,"opacity"))&&delete d.opacity,Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:N.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||vb.call(this.style)||vb.call(this.runtimeStyle)},a)}}),c&&Object.defineProperty(d,"opacity",c))):("float"in b||(a.runtimeStyle["float"]=
{valueOf:N.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}),"opacity"in b||(a.runtimeStyle.opacity={valueOf:N.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||vb.call(this.style)||vb.call(this.runtimeStyle)},a)}));return a.currentStyle});document.createDocumentFragment=function(){var a=C.call(fb,this);n.DocumentFragment===n.Document&&p(a,n.DocumentFragment.prototype);return ua(a)};Cb=(P.innerHTML="<x-x></x-x>",1===P.childNodes.length&&1===P.childNodes[0].nodeType);
oa="|"+oa+"|";ma.ielt9=g;D=ua(C.call(fb,document));Cb||(ua(document),document.head.insertAdjacentHTML("beforeend","<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>"));0===C.call(gb,document,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(Db=D.appendChild("createElement"in D&&D.createElement("div")||D.ownerDocument.createElement("div")),Eb=8===db?P.cloneNode:8>db?Q.cloneNode:f,Q.cloneNode=function(a){var b,c;na.test(this.nodeName)?
b=C.call(this.__nativeCloneNode__||Eb,this,a):(Db.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(/<(\w+)([^>]*)>[\W\w]*$/,"<$1$2></$1>"),Db.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=Db.firstChild,!b&&!a&&((c=c.match(qb))&&(c=c[1]),c&&(D.createElement(c),Db.innerHTML=c,b=Db.firstChild)));return D.appendChild(b)});P=T=W=sb=Cb=j;if(Q.ie||!(7<db)){var Ib=Array.prototype.unshift,bb=!document.readyState,Jb=["/a.ielt8.htc"],Kb="{behavior:",Lb=[],Mb,Nb,Ob,I,Pb=n.scrollTo,
Qb=n.scrollBy;for(T=Jb.length;0<=--T;)Kb+=' url("'+Jb[T]+'")';Kb+="}";bb&&(document.readyState="uninitialized");Q.ielt8=g;n.__ielt8__wontfix=Lb;var Aa=/\s*(\S+)\s*/g,Ba="(?=(^|.*\\s)$1(\\s|$))",Va=/^([\w\-\|]+)?((?:\.(?:[\w-]+))+)?$|^#([\w-]+$)/,Qa=/\s*([,>+~ ])\s*/g,Ra=/\~\=/g,Ta=/(^[>+~ ]?|,|\>|\+|~| ).*?(?=[,>+~ ]|$)/g,za=/\./g,Ma=/\s/g,xa=/^([,>+~ ])?([\|\*\w-]*)\#?([\w-]*)((?:\.?[\w-])*)(\[.+\])?(?:\:(.+))?$/,Ca=/^\[?['"]?(.*?)['"]?(?:([\*~&\^\$\@!]?=)['"]?(.*?)['"]?)?\]?$/,Ea=/^([^(]+)(?:\((.+)\))?$/,
Sa=/\-child\((\dn)\+(\d)\)/g,Ia=/(?:([-]?\d*)n)?(?:(%|-)(\d*))?/,Wa=/([,>+~ ])/,ya={"":1," ":1,",":1,">":2,"~":3,"+":4},Da={"":1,"=":2,"&=":3,"^=":4,"$=":5,"*=":6,"|=":7,"!=":8,"@=":9},Ha={"nth-child":0,"nth-last-child":1,"only-child":2,"first-child":3,"last-child":4,root:5,empty:6,checked:7,lang:8,enabled:9,disabled:10,selected:11,contains:12,not:13,matches:14,"read-only":15,"read-write":16},Ua=function(a){for(var b=a.length>>>0,c=new la,d=0;d<b;d++)d in a&&c.push(a[d]);return c},Ja=function(a){for(;(a=
a.nextSibling)&&1!=a.nodeType;);return a};T="matchesSelector";v[T]||(S[T]=v[T]=Na);T="matches";v[T]||(S[T]=v[T]=Na);T="querySelectorAll";document[T]||(S[T]=v[T]=document[T]=function(a,b){return Oa.call(this,a,l,b)});T="querySelector";document[T]||(S[T]=v[T]=document[T]=function(a,b){return Oa.call(this,a,g,b)[0]||j});T="getElementsByClassName";document[T]||(S[T]=v[T]=document[T]=function(a){a=RegExp(a.replace(Aa,Ba));for(var b=this.all,c,d=-1,e=[];c=b[++d];)c.className&&a.test(c.className)&&e.push(c);
return e});xb.e={};xb.c=function(a,b){if(b in this)return this[b];var c=a.nodeName;if(!(a=xb.e[c]))a=xb.e[c]=gb(c);return this[b]=a.getAttribute(b)!==j};S.setAttribute=function(a,b,c){if(c==f){var d=a.toLowerCase();c=1;E[d]!==f?a=E[d]:Ka[d]!==f?c=2:0!==d.indexOf("data-")&&!xb.c(this,d)&&(a=a.toUpperCase());b+=""}return Function.prototype.call.call(this.__setAttribute__,this,a,b,c)};S.getAttribute=function(a,b){var c;c=a.toLowerCase();var d,e;if(e=b==f)b=1;if(E[c]!==f)c=E[c];else{if(Ka[c]!==f)return C.call(this.__getAttribute__,
this,a,2);c=0!==c.indexOf("data-")&&!xb.c(this,c)?a.toUpperCase():a}d=C.call(this.__getAttribute__,this,c,b);d!==j?e&&(d+=""):!(c in this)&&"string"===typeof this[a]?(d=this[c]=this[a],this.__removeAttribute__(a),d+=""):d=j;return d};S.removeAttribute=function(a,b){var c,d;b==f&&(b=1,d=a.toLowerCase(),E[d]!==f?c=E[d]:Ka[d]!==f?b=2:0!==d.indexOf("data-")&&!xb.c(this,d)&&(c=a.toUpperCase()));return C.call(this.__removeAttribute__,this,c||a,b)};Q.hasAttribute||(Q.hasAttribute=function(a){return this.getAttribute(a)!==
j});var Z=function(a){return function(){return a}};Q.h=Z(1);Q.l=Z(2);Q.m=Z(3);Q.n=Z(4);Q.o=Z(7);Q.p=Z(8);Q.q=Z(9);Q.i=Z(10);Q.j=Z(11);Q.k=Z(16);Q.__ielt8__element_init__=function(){var a=this;a.element&&(a=a.element);"prepend"in a||(a.after=S.after,a.before=S.before,a.append=S.append,a.prepend=S.prepend,a.replace=S.replace,a.remove=S.remove);"isEqualNode"in a||(a.isEqualNode=Q.isEqualNode);"compareDocumentPosition"in a||(a.compareDocumentPosition=Q.compareDocumentPosition);"getElementsByClassName"in
a||(a.getElementsByClassName=S.getElementsByClassName);"addEventListener"in a||(a.addEventListener=n.addEventListener,a.removeEventListener=n.removeEventListener,a.dispatchEvent=n.dispatchEvent);"querySelector"in a||(a.querySelectorAll=S.querySelectorAll,a.querySelector=S.querySelector);"matchesSelector"in a||(a.matchesSelector=Na,a.matches=Na);"hasAttribute"in a||(a.hasAttribute=S.hasAttribute);"setSelectionRange"in a||(a.setSelectionRange=S.setSelectionRange);try{this.setAttribute!=S.setAttribute&&
(this.__setAttribute__=this.setAttribute,this.__getAttribute__=this.getAttribute,this.__removeAttribute__=this.removeAttribute,this.setAttribute=S.setAttribute,this.getAttribute=S.getAttribute,this.removeAttribute=S.removeAttribute),a.cloneNode!==Q.cloneNode&&(a.__nativeCloneNode__=a.cloneNode,a.cloneNode=Q.cloneNode),Q.contains&&(a.contains=Q.contains)}catch(b){Lb.push(a)}};Ob=Q.__ielt8_Node_behavior_apply=function(a){for(T=Jb.length;0<=--T;)try{a.addBehavior(Jb[T])}catch(b){}};Nb=Q.cloneNode;Q.cloneNode=
function(a){a=C.call(Nb||this.__nativeCloneNode__,this,a);Ob(a);return a};1!=[].unshift(0)&&(Array.prototype.unshift=function(){Ib.apply(this,arguments);return this.length});Mb=document.createElement;document.createElement=function(a){a=C.call(Mb,document,a);for(T=Jb.length;0<=--T;)try{a.addBehavior(Jb[T])}catch(b){}return a};n.XMLHttpRequest||(n.XMLHttpRequest=function(){var a;try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(b){a=new ActiveXObject("Microsoft.XMLHTTP")}var c=a.send;a.send=function(){this.setRequestHeader("If-Modified-Since",
"Sat, 1 Jan 2000 00:00:00 GMT");c.apply(this,arguments)}});!("pageXOffset"in n)&&n.attachEvent&&(n.pageXOffset=n.pageYOffset=0,I="CSS1Compat"===document.compatMode?function(){n.scrollX=n.pageXOffset=document.body.parentNode.scrollLeft;n.scrollY=n.pageYOffset=document.body.parentNode.scrollTop}:function(){n.scrollX=n.pageXOffset=document.body.scrollLeft;n.scrollY=n.pageYOffset=document.body.scrollTop},n.attachEvent("onscroll",I),n.scroll=n.scrollTo=function(a,b){Pb(a,b);I()},n.scrollBy=function(a,
b){Qb(a,b);I()});document.addEventListener("DOMContentLoaded",Xa);n.attachEvent("onload",cb);var Rb=Kb,$=document.getElementById("ielt8_style_prev_for_behaviour"),Sb="";$&&(Sb=$.getAttribute("data-url")||"",$.id="");Sb&&Rb.replace(" url("," url("+Sb+") url(");$=gb("style");$.id="ielt8_style_prev_for_behaviour";$.type="text/css";$.setAttribute("data-url",Rb.replace("{behavior:","").replace(")}",")"));$.styleSheet.cssText="*"+Rb;document.head.appendChild($);Kb=T=j}}
}();
