/* ES6/DOM4 polyfill for IE8 | @version 0.8.2 | MIT License | github.com/termi */
void function(y){var j=void 0,m=!0,n=null,s=!1;function O(){return function(){}};function z(a){if(!("__isFixed"in a||a.isTrusted===s)){var b="button"in a&&a.button;a.__isFixed=m;if("click"===a.type||"dblclick"===a.type)a.detail===j&&(a.detail="click"===a.type?1:2),!a.button&&z.b!==j&&(b=z.b);y(a,F);a.defaultPrevented||(a.defaultPrevented=s);a.target||(a.target=a.srcElement||document);a.relatedTarget===j&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==n&&(a.pageX=a.clientX+P()-(r.clientLeft||0),a.pageY=
a.clientY+Q()-(r.clientTop||0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new fa);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);"currentTarget"in a||(a.currentTarget=this);a.keyCode||(a.keyCode=a.charCode||a.which);!a.attrName&&a.propertyName&&(a.attrName=ga.call(a.propertyName,".")[0]);return a}}function A(a){if(z!==j){var b=this._,c,d,g,f,E,p,k,l;if(!b.__stop_events__){c=[];d=[];f="_e_8vj"+(qa?"-":"");if(!b||!b[f])if("__dom0__"in a)b||(b={}),b[f]||(b[f]={});
else return;a||(a=e.event);if("__custom_event"in a)g=a;else if(!(g=a.__customEvent__))a.bubbles==j&&(a.bubbles=m),a.cancelable==j&&(a.cancelable=m),g=a.__customEvent__=new w(a),g.initEvent(a.type,a.bubbles,a.cancelable),z.call(this,g),g.k=m,g.__custom_event=n;g.ietl9_event=a;a.currentTarget=this;"__dom0__"in a&&(p=a.__dom0__);if((b=b[f][g.type])||p)E=b?G.call(b):[],p&&E.unshift(p);if(E&&E.length){for(;p=E.shift();)if(p&&(!(l=p[H])||"_"+l in b)){"object"===typeof p&&(k=p,p=p.handleEvent);try{if(p&&
(g.result=t.call(p,k||this,g))===s)g.defaultPrevented===s&&g.returnValue!==s&&g.preventDefault(),g.stopPropagation()}catch(h){c.push(h),d.push(h.message)}if(g.__stopNow)break}a.returnValue=g.returnValue;a.cancelBubble=g.cancelBubble;1==c.length?K(c[0]):1<c.length&&(d=Error("Multiple errors thrown : "+g.type+" :  : "+d.join("|")),d.errors=c,K(d))}this===document&&(!g.cancelBubble&&3===g.eventPhase)&&(A.call(this.defaultView,g),a.cancelBubble=m)}}}function U(a){var b=this.__orig__createElement__(a);
if(ha.test(a))return b;~L.indexOf("|"+a+"|")||(V.push(a),L+=a+"|",(B.__orig__createElement__||B.createElement)(a));return B.appendChild(b)}function W(a){var b=-1;if(a.createElement){for(;++b<V.length;)a.createElement(V[b]);a.createElement!==U&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=U)}return a}var e=this,v=e.eval&&e.eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||n;if(9>v){e.Element||((e.Element=e.ActiveXObject).prototype.ie=
m);e.HTMLElement||(e.HTMLElement=e.Element);e.Node||(e.Node=e.Element);var q;e.DocumentFragment||(e.DocumentFragment=e.Document||e.HTMLDocument||(q=O(),q.prototype={},q));e.Document||(e.Document=e.DocumentFragment);e._={ielt9shims:[],orig_:e._,isObject:function(a){return a&&"[object Object]"===X.call(a)&&"function"===typeof a.constructor&&"[object Function]"===X.call(a.constructor)}};var k=e._.ielt9shims,Y=document.createDocumentFragment,ia=document.createElement,ja=document.createTextNode,r=document.documentElement,
K=function(a){throw"object"==typeof a&&a instanceof Error?a:Error(a);},ka=function(a){var b=Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},la=function(a,b){for(var c in b)if(S(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(d){}},ta=String.prototype.trim||function(){for(var a=this.replace(ra,""),b=a.length;sa.test(a.charAt(--b)););return a.slice(0,b+1)},ga=String.prototype.split,ua=String.prototype.substr,G=Array.prototype.slice,Z=Array.prototype.splice,
$=Function.prototype.apply,t=Function.prototype.call,x=Function.prototype.bind||function(a,b){var c=this,d=G.call(arguments,1);return function(){return $.call(c,a,d.concat(G.call(arguments)))}},C,X=Object.prototype.toString,S=x.call(t,Object.prototype.hasOwnProperty);q=document.createElement("p");var l=e.Node.prototype,u=e.Element.prototype,va=q.contains||l.contains,fa=Date,wa=/^\<([\w\:\-]*)[\>\ ]/i,ra=/^\s+/,sa=/\s/,aa,f,D,ba=/alpha\(opacity=([^\)]+)\)/,T=function(){var a=(this.filter||"").match(ba);
return a?parseInt(a[1])/100+"":""},ca={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))",
"i"))||[])[2]||""},item:O()},M={"for":"htmlFor","class":"className",value:"defaultValue"},da={action:n,cite:n,codebase:n,data:n,href:n,longdesc:n,lowsrc:n,src:n,usemap:n},I={id:m,value:m,checked:m,disabled:m,ismap:m,multiple:m,readonly:m,selected:m},R={style:{get:function(){return this.style&&this.style.cssText?this.style.cssText:n},set:function(a){this.style&&(this.style.cssText=a);return a},remove:function(){return this.style&&this.style.cssText?(this.style.cssText="",m):s},has:function(){return!(!this.style||
!this.style.cssText)}}},w,J,F,H="uuid"+(Math.random()+"").substr(2),xa=1,ya=O(),qa=s,ma,L="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|main|nav|output|progress|section|source|summary|time|video",V=L.split("|"),ha=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,h,B,
N,na,P,Q;f=document.createElement("iframe");f.style.display="none";(document.body||r).appendChild(f);f.contentWindow.document.write("<script>parent._.NodeList=Array;parent._.EMP=Object.prototype\x3c/script>");C=e._.EMP;delete e._.EMP;delete C.constructor;delete C.hasOwnProperty;delete C.propertyIsEnumerable;delete C.isPrototypeOf;delete C.toLocaleString;delete C.toString;delete C.valueOf;C.__proto__=n;k.push(function(){var a=Object.create;Object.create=function(b){b===n&&(arguments[0]=C);a.apply(this,
arguments)}});"CSS1Compat"===document.compatMode?(P=function(){return r.scrollLeft},Q=function(){return r.scrollTop}):(P=function(){return document.body.scrollTop},Q=function(){return document.body.scrollLeft});document.head||(document.head=document.getElementsByTagName("head")[0]);"defaultView"in document||(document.defaultView=document.parentWindow);f=s;try{f=isNaN.apply(n,{})}catch(Fa){}f||(Function.prototype.apply=function(a,b){var c;if(!b||!(c=+b.length))return t.call(this,a);if("object"!==typeof b||
0>c||"callee"in b&&"caller"in b||"[object Array]"==X.call(b))return $.call(this,a,b);switch(c){case 1:return t.call(this,a,b[0]);case 2:return t.call(this,a,b[0],b[1]);case 3:return t.call(this,a,b[0],b[1],b[2]);case 4:return t.call(this,a,b[0],b[1],b[2],b[3]);case 5:return t.call(this,a,b[0],b[1],b[2],b[3],b[4]);case 6:return t.call(this,a,b[0],b[1],b[2],b[3],b[4],b[5]);case 7:return t.call(this,a,b[0],b[1],b[2],b[3],b[4],b[5],b[6])}return $.call(this,a,Array.from(b))});"b"!=="ab".substr(-1)&&(String.prototype.substr=
function(a,b){return ua.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if("te".split(/(s)*/)[1]!=j||3!="1_1".split(/(_)/).length)aa=/()??/.exec("")[1]===j,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===j&&0===b?[]:ga.call(c,a,b);var d=[],g=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.extended?"x":"")+(a.sticky?"y":""),e=0,f,p,k;a=RegExp(a.source,g+"g");c+="";aa||(f=RegExp("^"+a.source+"$(?!\\s)",g));b=b===j?4294967295:b>>>0;if(!b)return[];for(;p=a.exec(c);){g=
p.index+p[0].length;if(g>e&&(d.push(c.slice(e,p.index)),!aa&&1<p.length&&p[0].replace(f,function(){for(var a=1,b=arguments.length-2;a<b;a++)arguments[a]===j&&(p[a]=j)}),1<p.length&&p.index<c.length&&d.push.apply(d,p.slice(1)),k=p[0].length,e=g,d.length>=b))break;a.lastIndex===p.index&&a.lastIndex++}e===c.length?(k||!a.test(""))&&d.push(""):d.push(c.slice(e));return d.length>b?d.slice(0,b):d};e.DOMException||(f=(e.DOMException=O()).prototype=Error(),f.INDEX_SIZE_ERR=1,f.HIERARCHY_REQUEST_ERR=3,f.WRONG_DOCUMENT_ERR=
4,f.INVALID_CHARACTER_ERR=5,f.NO_MODIFICATION_ALLOWED_ERR=7,f.NOT_FOUND_ERR=8,f.NOT_SUPPORTED_ERR=9,f.INVALID_STATE_ERR=11,f.SYNTAX_ERR=12,f.INVALID_MODIFICATION_ERR=13,f.NAMESPACE_ERR=14,f.INVALID_ACCESS_ERR=15);"pageXOffset"in e||k.push(function(){Object.defineProperty(e,"pageXOffset",{get:P});Object.defineProperty(e,"pageYOffset",{get:Q})});D=e.Event=function(){K("")};J={initEvent:function(a,b,c){(a==j||b==j||c==j)&&K("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=c;this.k=s;
this.target=n;this.timeStamp||(this.timeStamp=+new fa)},initCustomEvent:function(a,b,c,d){J.initEvent.call(this,a,b,c);this.detail=d},initUIEvent:function(a,b,c,d,g){J.initCustomEvent.call(this,a,b,c,g);this.view=d},initMouseEvent:function(a,b,c,d,g,e,f,p,k,l,h,q,r,t,u){J.initUIEvent.call(this,a,b,c,d,g);this.screenX=e;this.screenY=f;this.clientX=p;this.clientY=k;this.ctrlKey=l;this.altKey=h;this.shiftKey=q;this.metaKey=r;this.button=t;this.relatedTarget=u}};F=D.prototype={constructor:D,preventDefault:function(){this.cancelable!==
s&&(w.a.call(this).returnValue=this.returnValue=s,w.f.call(this),this.defaultPrevented=m)},stopPropagation:function(){w.a.call(this).cancelBubble=this.cancelBubble=m;w.f.call(this)}};F.stopImmediatePropagation=function(){this.__stopNow=m;this.stopPropagation()};F.defaultPrevented=s;for(f in J)S(J,f)&&(F[f]=function(){J[arguments.callee.name].apply(this,arguments);la(this.ietl9_event,this)},F[f].name=f);w=function(a){this.ietl9_event=a;a.returnValue=m;la(this,a)};w.a=function(){var a=this.ietl9_event;
a===j?K("WRONG_THIS_ERR"):a===n&&(a=w.a.j);return a};w.a.j={};w.f=function(){this.ietl9_event&&(this.ietl9_event=n)};D=O();D.prototype=F;D=new D;D.constructor=w;w.prototype=D;q.addEventListener||((e.Text&&e.Text.prototype||l).addEventListener=l.addEventListener=r.addEventListener=e.addEventListener=document.addEventListener=function(a,b,c){if("function"==typeof b||"object"===typeof b&&b.handleEvent){var d=this,g=d._,f=s;d==e&&(!("_"in document)||!("_e_8vj"in document._)||!(a in document._._e_8vj))&&
document.addEventListener(a,ya,c);g||(g=d._={});switch(a){case "DOMContentLoaded":if("complete"==document.readyState)return;d===e&&(d=document);f=m;if(!ma){ma=m;var E=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(E,50);return}A.call(d,{type:a,isTrusted:m,__custom_event:j})};if("createEventObject"in document&&"doScroll"in document.documentElement)try{e.frameElement||E()}catch(p){}}break;case "load":"tagName"in d&&-1!="SCRIPT|IFRAME".indexOf(d.tagName.toUpperCase())&&
(f=m,d.onreadystatechange=function(){"loaded"===d.readyState&&(d.onreadystatechange=n,d.attachEvent("onreadystatechange",x.call(A,d,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}d.setInterval&&(d!=e&&!d.frameElement)&&(d=e);b[H]||(b[H]=++xa);if(!(c=g._h_9e2))c=g._h_9e2=x.call(A,d);g._e_8vj||(g._e_8vj={});a in g._e_8vj?g=g._e_8vj[a]:(g=g._e_8vj[a]=[],f||d.attachEvent("on"+a,c));"_"+b[H]in g||(g.push(b),g["_"+b[H]]=n)}},l.addEventListener.__shim__=m,(e.Text&&e.Text.prototype||
l).removeEventListener=l.removeEventListener=r.removeEventListener=e.removeEventListener=document.removeEventListener=function(a,b){var c=this._,d,g,e,f,p;if(!("function"!==typeof b&&!("object"===typeof b&&b.handleEvent)||!b[H]||!c))if(d=c._h_9e2){g=c._e_8vj&&c._e_8vj[a];for(f=0;p=g[f++];)if(p===b){Z.call(g,f-1,1);delete g["_"+b[H]];break}if(!g.length){this.detachEvent("on"+a,d);delete c._e_8vj[a];for(e in c._e_8vj)if(S(c._e_8vj,e))return;delete c._e_8vj;delete c._h_9e2}}},l.removeEventListener.__shim__=
m,document.attachEvent("onmousedown",function(){z.b=event.button}),document.attachEvent("onclick",function(){z.b=j}));q.dispatchEvent||((e.Text&&e.Text.prototype||l).dispatchEvent=l.dispatchEvent=r.dispatchEvent=e.dispatchEvent=document.dispatchEvent=function(a){if(!a.type)return m;a.returnValue||(a.returnValue=m);a.cancelBubble&&(a.cancelBubble=s);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===e||-2146827850===b.number&&!(a.bubbles=s)){a.__custom_event=
m;for(var c=a.target=this,d="on"+a.type;!a.cancelBubble&&c;)(d in c&&"function"==typeof c[d]&&(a.__dom0__=c[d])||"_"in c&&"_e_8vj"in c._)&&A.call(c,a),c=a.bubbles?c===document?document.defaultView:c.parentNode:n,"__dom0__"in a&&(a.__dom0__=j,delete a.__dom0__);return!a.cancelBubble}K(b)}},l.dispatchEvent.__shim__=m);document.createEvent||(document.createEvent=function(){return new w(document.createEventObject())});k.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),d,e,f,k,l,h,q,r;
if(!("INPUT"!=c&&"TEXTAREA"!=c)){"unknown"!=typeof document.activeElement&&(h=document.activeElement);b=document.selection;this._&&(q=this._.__stop_events__,this._.__stop_events__=m);h&&h._&&(r=h._.__stop_events__,h._.__stop_events__=m);try{this.focus(),d=b.createRange(),e=d.duplicate(),"TEXTAREA"==c?(f=this.value,d=e,a?(d.moveEnd("character",f.length),l=""==d.text?f.length:f.lastIndexOf(d.text)):(d.moveStart("character",-f.length),l=d.text.length)):(e.moveToElementText(this),e.setEndPoint("EndToEnd",
d),k=e.text.length-d.text.length,l=a?k:k+d.text.length),h&&h.focus&&h.focus()}catch(t){l=j}this._&&!q&&delete this._.__stop_events__;h&&(h._&&!r)&&delete h._.__stop_events__;return l}}function b(a,b){if(a!=j){b==j&&(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(m),c.moveStart("character",a),c.moveEnd("character",b-a),c.select())}}var c=e.HTMLTextAreaElement&&e.HTMLTextAreaElement.prototype,d={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,
m)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},set:function(c){b.call(this,a.call(this,m),c);return c}}};Object.defineProperties(e.HTMLInputElement&&e.HTMLInputElement.prototype||u,d);c&&Object.defineProperties(c,d)});document.doctype===n&&7<v&&k.push(function(){var a=document.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});Object.defineProperty(document,"doctype",{configurable:m,enumerable:s,get:function(){return a}})});
l.contains||(l.contains=va);t.call(ja,document,"").contains||(e.Text&&e.Text.prototype?k.push(x.call(y,n,Text.prototype,l)):document.createTextNode=function(a){a=t.call(ja,this,a);a.contains=l.contains;return a});!t.call(Y,document).contains&&(e.HTMLDocument&&e.HTMLDocument.prototype)&&k.push(x.call(y,n,e.HTMLDocument.prototype,l));"children"in q||k.push(function(){Object.defineProperty(u,"children",{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});
k.push(function(){function a(a,c){var d;try{a:{var e=a;"element"in e&&("defaults"in e&&"document"in e)&&(e=e.element);var f=e.getBoundingClientRect(),h,k,l;if((l=e.ownerDocument)!==document){if(h=l&&l.body,k=l&&l.documentElement,!h||!k){d=c?f.left:f.top;break a}}else h=document.body,k=r;d=c?f.left+P()-(k.clientLeft||h.clientLeft||0):f.top+Q()-(k.clientTop||h.clientTop||0)}}catch(q){d=a;e=0;for(f=c?"offsetLeft":"offsetTop";d;)e+=parseInt(d[f],10),d=d.offsetParent;d=e}return d}Object.defineProperties(u,
{offsetLeft:{get:function(){return a(this,m)}},offsetTop:{get:function(){return a(this)}}})});q.childElementCount==j&&k.push(function(){Object.defineProperties(u,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=
this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});document.ELEMENT_NODE||(f={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},y(document,f),y(l,f),y(e.Node,f));"textContent"in q||k.push(function(){Object.defineProperty(l,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in
this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in q||(document.isEqualNode=r.isEqualNode=l.isEqualNode=function(a){var b,c;if(a===n||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return s;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return s;b=0;for(c=this.attributes.length;b<c;b++){var d=this.attributes[length],e=a.getAttributeNS(d.namespaceURI,
d.localName);if(e===n||e.value!==d.value)return s}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return s;b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===s)return s;return m});document.importNode||(document.importNode=function(a,b){switch(a.nodeType){case 1:var c=document.createElement(a.nodeName),d=a.attributes,e,f,h;if(d&&0<d.length){f=
0;for(h=d.length;f<h;)d=a.attributes[f++],c.setAttribute(d.nodeName,a.getAttribute(d.nodeName))}if(b&&(e=a.childNodes)&&0<e.length){f=0;for(h=e.length;f<h;)c.appendChild(document.importNode(e[f++],b))}return c;case 3:case 4:case 8:return document.createTextNode(a.nodeValue)}ka("NOT_SUPPORTED_ERR");return n},document.importNode.shim=m);f="compareDocumentPosition";f in document||(k=h||"DOCUMENT_POSITION_",r[f]=document[f]=l[f]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=
a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0},h="DISCONNECTED",r[k+h]=document[k+h]=l[k+h]=1,h="PRECEDING",r[k+h]=document[k+h]=l[k+h]=2,h="FOLLOWING",r[k+h]=document[k+h]=l[k+h]=4,h="CONTAINS",r[k+h]=document[k+h]=l[k+h]=8,h="CONTAINED_BY",r[k+h]=document[k+h]=l[k+h]=16);e.getComputedStyle||(e.getComputedStyle=function(a){var b=a.currentStyle||a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=
x.call(ca.getPropertyValue,a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=e.getComputedStyle.i,a.runtimeStyle.getPropertyPriority=e.getComputedStyle.h,a.runtimeStyle.item=ca.item);var c,d,f;(d=e.CSSStyleDeclaration)&&(d=d.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(d,"float"))&&delete d["float"],f=x.call(e.getComputedStyle.d,a),Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:f,toString:f},configurable:m,writable:m}),c&&
Object.defineProperty(d,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(d,"opacity"))&&delete d.opacity,f=x.call(e.getComputedStyle.e,a),Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:f,toString:f},configurable:m,writable:m}),c&&Object.defineProperty(d,"opacity",c))):("float"in b||(f=x.call(e.getComputedStyle.d,a),a.runtimeStyle["float"]={valueOf:f,toString:f}),"opacity"in b||(f=x.call(e.getComputedStyle.e,a),a.runtimeStyle.opacity={valueOf:f,toString:f}));return a.currentStyle},
e.getComputedStyle.e=function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||T.call(this.style)||T.call(this.runtimeStyle)},e.getComputedStyle.d=function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},e.getComputedStyle.i=function(){ka("NO_MODIFICATION_ALLOWED_ERR")},e.getComputedStyle.h=function(){return""});document.createDocumentFragment=function(){var a=t.call(Y,this);e.DocumentFragment===e.Document&&y(a,e.DocumentFragment.prototype);return W(a)};h=(q.innerHTML="<x-x></x-x>",
1===q.childNodes.length&&1===q.childNodes[0].nodeType);L="|"+L+"|";U.ielt9=m;B=W(t.call(Y,document));h||(W(document),document.head.insertAdjacentHTML("beforeend","<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>"));0===t.call(ia,document,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(N=B.appendChild("createElement"in B&&B.createElement("div")||B.ownerDocument.createElement("div")),na=8===v?q.cloneNode:8>v?l.cloneNode:
j,l.cloneNode=function(a){var b,c;ha.test(this.nodeName)?b=t.call(this.__nativeCloneNode__||na,this,a):(N.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(/<(\w+)([^>]*)>[\W\w]*$/,"<$1$2></$1>"),N.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=N.firstChild,!b&&!a&&((c=c.match(wa))&&(c=c[1]),c&&(B.createElement(c),N.innerHTML=c,b=N.firstChild)));return B.appendChild(b)});q=function(a){for(var b=[];a--;)b.unshift(a);return b};v=[];x.call(v.splice,v,0,0).apply(n,q(20));
x.call(v.splice,v,0,0).apply(n,q(26));q=v.length;v.splice(5,0,"XXX");v=q+1==v.length?m:j;v||(Array.prototype.splice=function(a,b){var c,d=G.call(arguments,2);c=d.length;if(!arguments.length)return[];a===j&&(a=0);b===j&&(b=this.length-a);if(0<c){if(0>=b){if(a==this.length)return this.push.apply(this,d),[];if(0==a)return this.unshift.apply(this,d),[]}c=G.call(this,a,a+b);d.push.apply(d,G.call(this,a+b,this.length));d.unshift.apply(d,G.call(this,0,a));d.unshift(0,this.length);Z.apply(this,d);return c}return Z.call(this,
a,b)});var za=/\s+(?=\S)|^/g,ea=u.getAttribute,Aa=u.setAttribute,oa=u.removeAttribute;I.g={};I.c=function(a,b){if(b in this)return this[b];var c=a.nodeName;if(!(a=I.g[c]))a=I.g[c]=ia(c);c=ea.call(a,b)!==n;c||(c=(c=a.constructor)&&(c=c.prototype)&&"object"===typeof(c=Object.getOwnPropertyDescriptor(c,b))&&"get"in c&&/\[native\scode\]/.test(c.get+""));return this[b]=c};u.setAttribute=function(a,b){var c=a.toLowerCase(),d=a,e,f;if(c in R)return R[c].set.call(this,b);M[c]!==j?d=M[c]:da[c]===j&&(-1===
c.indexOf("-")&&!I.c(this,c))&&(d=a.toUpperCase());d!=a&&a in this&&(!(f=this.attributes)||!((f=f[a])&&f.expando===s))?(f=this[a],e=m):f=n;b+="";d!=a?(this[d]=b,e&&(this[a]=f)):Aa.call(this,d,b)};u.getAttribute=function(a){var b;b=a.toLowerCase();var c;if((c=R[b])!==j)return c.get.call(this);if(M[b]!==j)return ea.call(this,M[b]);if(da[b]!==j)return(c=this.attributes)&&(c=c[b])&&(c=c.nodeValue)&&c+""||n;if(-1===b.indexOf("-")&&!I.c(this,b))b=a.toUpperCase();else return ea.call(this,a);c=this[b];c||
(!(b in this)&&"string"===typeof this[a]?(c=this[b]=this[a],delete this[a]):c=j);return c!==j?c+"":n};u.removeAttribute=function(a){var b;b=a.toLowerCase();var c;if(b in R)return R[b].remove.call(this);if(M[b]!==j)return oa.call(this,M[b]);if(da[b]===j&&-1===b.indexOf("-")&&!I.c(this,b))b=a.toUpperCase();else return oa.call(this,a);((c=b in this)||this.getAttribute(a)!==n)&&b in this&&delete this[b];return c};u.hasAttribute=function(a){return this.getAttribute(a)!==n};f="getElementsByClassName";!u[f]&&
document.querySelectorAll&&(u[f]=r[f]=document[f]=function(a){return!a||!(a=ta.call(a))?[]:t.call(this.querySelectorAll||document.querySelectorAll,this,a.replace(za,"."))});if(f=e.CSSStyleDeclaration)"opacity"in r.style||(Object.defineProperty(f.prototype,"opacity",{get:T,set:function(a){"object"==typeof a&&(a=a.valueOf());this.opacity!==T.call(this)&&delete this.opacity;a=a&&"alpha(opacity="+(0.9999<=a?"100":0>a?0:~~(100*a))+")"||"";this.filter=ba.test(this.filter)?this.filter.replace(ba,a):this.filter+
(" "+a);this.msOpacity=this.opacity}}),Object.defineProperty(f.prototype,"msOpacity",{value:""})),"float"in r.style||Object.defineProperty(f.prototype,"float",{get:function(){return this.styleFloat},set:function(a){return this.styleFloat=a}}),"getPropertyValue"in f||function(a){for(var b in a)S.call(a,b)&&(this[b]=a[b])}.call(f,ca);if((f=e.TextRectangle)&&(f=f.prototype))Object.defineProperty(f,"width",{get:function(){return this.right-this.left}}),Object.defineProperty(f,"height",{get:function(){return this.bottom-
this.top}});var Ba=document.querySelectorAll,Ca=document.querySelector,Da=u.querySelectorAll,Ea=u.querySelector,pa=function(a){for(var b=a.length>>>0,c=[],d=0;d<b;d++)d in a&&c.push(a[d]);return c};document.querySelectorAll=function(){return pa(Ba.apply(this,arguments))};document.querySelector=function(){return Ca.apply(this,arguments)};u.querySelectorAll=function(){return pa(Da.apply(this,arguments))};u.querySelector=function(){return Ea.apply(this,arguments)};q=f=D=h=n}}.call(window,function(y,
z){for(var A in z)Object.prototype.hasOwnProperty.call(z,A)&&!Object.prototype.hasOwnProperty.call(y,A)&&(y[A]=z[A]);return y});
