/* ES6/DOM4 polyfill for IE8 | @version 0.7 final | MIT License | github.com/termi */
;(function() {
var j=void 0,l=!0,n=null,q=!1;function J(){return function(){}}
(function(d,t){function u(a){if(!("__isFixed"in a)){var b="button"in a&&a.button;a.__isFixed=l;if("click"===a.type||"dblclick"===a.type)a.detail===j&&(a.detail="click"===a.type?1:2),!a.button&&u.b!==j&&(b=u.b);t(a,A);a.defaultPrevented||(a.defaultPrevented=q);a.target||(a.target=a.srcElement||document);a.relatedTarget===j&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==n&&(a.pageX=a.clientX+K()-(m.clientLeft||0),a.pageY=a.clientY+L()-(m.clientTop||
0));!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new $);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);"currentTarget"in a||(a.currentTarget=this);!a.attrName&&a.propertyName&&(a.attrName=aa.call(a.propertyName,".")[0]);return a}}function M(a){if(u!==j){var b=this._,c,f,h,d;if(!b.__stop_events__){c=[];f=[];d="_e_8vj"+(ja?"-":"");if(!b||!b[d])if("__dom0__"in a)b||(b={}),b[d]||(b[d]={});else return;a||(a=window.event);if("__custom_event"in a)h=a;else if(!(h=a.__customEvent__))a.bubbles==
j&&(a.bubbles=l),a.cancelable==j&&(a.cancelable=l),h=a.__customEvent__=new s(a),h.initEvent(a.type,a.bubbles,a.cancelable),u.call(this,h),h.e=l,h.__custom_event=j;h.ietl9_event=a;a.currentTarget=this;b=b[d][h.type];"__dom0__"in a&&((b||(b=[]))[0]=a.__dom0__);if(b){for(var e in b)if(B(b,e)){d=b[e];var g;"object"===typeof d&&(g=d,d=d.handleEvent);try{if(d&&(h.result=y.call(d,g||this,h))===q)h.preventDefault(),h.stopPropagation()}catch(r){c.push(r),f.push(r.message),console&&console.error(r)}if(h.__stopNow)break}b[0]=
j;delete b[0];a.returnValue=h.returnValue;a.cancelBubble=h.cancelBubble;1==c.length?C(c[0]):1<c.length&&(f=Error("Multiple errors thrown : "+h.type+" :  : "+f.join("|")),f.f=c,C(f))}this===document&&(!h.cancelBubble&&3===h.eventPhase)&&(M.call(this.defaultView,h),a.cancelBubble=l)}}}function D(){}function ka(){var a=document.querySelectorAll("#z").constructor.prototype;if(a&&a!==Array.prototype)for(var b in Q)B(b,Q)&&(a[b]||(a[b]=function(){return N.call(Array.prototype[b],Array.from(this),arguments)}))}
function R(a){var b=this.__orig__createElement__(a);if(ba.test(a))return b;~F.indexOf("|"+a+"|")||(S.push(a),F+=a+"|",(v.__orig__createElement__||v.createElement)(a));return v.appendChild(b)}function T(a){var b=-1;if(a.createElement){for(;++b<S.length;)a.createElement(S[b]);a.createElement!==R&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=R)}return a}var P=window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||j;if(9>
P){d.Element||((d.Element=ActiveXObject).prototype.ie=l);d.HTMLElement||(d.HTMLElement=d.Element);d.Node||(d.Node=d.Element);var O;d.DocumentFragment||(d.DocumentFragment=d.Document||d.HTMLDocument||(O=J(),O.prototype={},O));d.Document||(d.Document=d.DocumentFragment);d._={ielt9shims:[],orig_:d._};var g=d._.ielt9shims,U=document.createDocumentFragment;O=document.createElement;var ca=document.createTextNode,m=document.documentElement,C=function(a){throw a instanceof Error?a:Error(a);},da=function(a){var b=
Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},ea=function(a,b){for(var c in b)if(B(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(f){}},na=String.prototype.trim||function(){for(var a=this.replace(la,""),b=a.length;ma.test(a.charAt(--b)););return a.slice(0,b+1)},aa=String.prototype.split,oa=String.prototype.substr,fa=Array.prototype.slice,N=Function.prototype.apply,y=Function.prototype.call,z=Function.prototype.bind||function(a,b){var c=this,f=
fa.call(arguments,1);return function(){return N.call(c,a,f.concat(fa.call(arguments)))}},B=z.call(Function.prototype.call,Object.prototype.hasOwnProperty),w=document.createElement("p"),k=d.Node.prototype,p=d.Element.prototype,pa=w.contains||k.contains,$=Date,qa=/^\<([\w\:\-]*)[\>\ ]/i,la=/^\s+/,ma=/\s/,V,e,x,Q="every filter forEach indexOf join lastIndexOf map reduce reduceRight reverse slice some toString".split(" "),W=/alpha\(opacity=([^\)]+)\)/,G=function(){var a=(this.filter||"").match(W);return a?
parseInt(a[1])/100+"":""},X={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))",
"i"))||[])[2]||""},item:J()},H={"for":"htmlFor","class":"className",value:"defaultValue"},Y={value:n,checked:n,disabled:n,ismap:n,multiple:n,readonly:n,selected:n},s,E,A,ra=1,sa=J(),ja=q,ga,F="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|nav|output|progress|section|source|summary|time|video",S=F.split("|"),ba=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,
i,v,I,ha,K,L;"CSS1Compat"===document.compatMode?(K=function(){return m.scrollLeft},L=function(){return m.scrollTop}):(K=function(){return document.body.scrollTop},L=function(){return document.body.scrollLeft});document.head||(document.head=document.getElementsByTagName("head")[0]);"defaultView"in document||(document.defaultView=document.parentWindow);e=q;try{e=isNaN.apply(n,{})}catch(va){}e||(Function.prototype.apply=function(a,b){try{return b!=j?N.call(this,a,b):N.call(this,a)}catch(c){return(-2146823260!=
c.number||b.length===j||"string"===typeof b)&&C(c),N.call(this,a,Array.from(b))}});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return oa.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if("te".split(/(s)*/)[1]!=j||3!="1_1".split(/(_)/).length)V=/()??/.exec("")[1]===j,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===j&&0===b?[]:aa.call(c,a,b);var f=[],h=0,d=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.g?"y":""),e=RegExp(a.source,d+"g"),g=n,r,i,c=
c+"";V||(g=RegExp("^"+e.source+"$(?!\\s)",d));if(b===j||0>+b)b=Infinity;else if(b=Math.floor(+b),!b)return[];for(;r=e.exec(c);){d=r.index+r[0].length;if(d>h&&(f.push(c.slice(h,r.index)),!V&&1<r.length&&r[0].replace(g,function(){for(var a=1,b=arguments,c=b.length-2;a<c;a++)b[a]===j&&(r[a]=j)}),1<r.length&&r.index<c.length&&f.push.apply(f,r.slice(1)),i=r[0].length,h=d,f.length>=b))break;e.lastIndex===r.index&&e.lastIndex++}h===c.length?(i||!e.test(""))&&f.push(""):f.push(c.slice(h));return f.length>
b?f.slice(0,b):f};d.DOMException||(e=(d.DOMException=J()).prototype=Error(),e.INDEX_SIZE_ERR=1,e.HIERARCHY_REQUEST_ERR=3,e.WRONG_DOCUMENT_ERR=4,e.INVALID_CHARACTER_ERR=5,e.NO_MODIFICATION_ALLOWED_ERR=7,e.NOT_FOUND_ERR=8,e.NOT_SUPPORTED_ERR=9,e.INVALID_STATE_ERR=11,e.SYNTAX_ERR=12,e.INVALID_MODIFICATION_ERR=13,e.NAMESPACE_ERR=14,e.INVALID_ACCESS_ERR=15,e.TYPE_MISMATCH_ERR=17);"pageXOffset"in d||g.push(function(){Object.defineProperty(d,"pageXOffset",{get:K});Object.defineProperty(d,"pageYOffset",{get:L})});
x=d.Event=function(){C("")};E={initEvent:function(a,b,c){(a==j||b==j||c==j)&&C("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=c;this.e=q;this.target=n;this.timeStamp||(this.timeStamp=+new $)},initCustomEvent:function(a,b,c,f){E.initEvent.call(this,a,b,c);this.detail=f},initUIEvent:function(a,b,c,f,h){E.initCustomEvent.call(this,a,b,c,h);this.view=f},initMouseEvent:function(a,b,c,f,h,d,e,g,r,i,k,m,p,s,t){E.initUIEvent.call(this,a,b,c,f,h);this.screenX=d;this.screenY=e;this.clientX=
g;this.clientY=r;this.ctrlKey=i;this.altKey=k;this.shiftKey=m;this.metaKey=p;this.button=s;this.relatedTarget=t}};A=x.prototype={constructor:x,preventDefault:function(){this.cancelable!==q&&(s.a.call(this).returnValue=this.returnValue=q,s.c.call(this),this.defaultPrevented=l)},stopPropagation:function(){s.a.call(this).cancelBubble=this.cancelBubble=l;s.c.call(this)}};A.stopImmediatePropagation=function(){this.__stopNow=l;this.stopPropagation()};A.defaultPrevented=q;for(e in E)B(E,e)&&(A[e]=function(){E[arguments.callee.name].apply(this,
arguments);ea(this.ietl9_event,this)},A[e].name=e);s=function(a){this.ietl9_event=a;a.returnValue=l;ea(this,a)};s.a=function(){var a=this.ietl9_event;a===j?C("WRONG_THIS_ERR"):a===n&&(a=s.a.d);return a};s.a.d={};s.c=function(){this.ietl9_event&&(this.ietl9_event=n)};x=J();x.prototype=A;x=new x;x.constructor=s;s.prototype=x;document.addEventListener||(k.addEventListener=m.addEventListener=d.addEventListener=document.addEventListener=function(a,b,c){if("function"==typeof b||"object"===typeof b&&b.handleEvent){var f=
this,h=f._,e=q;f==d&&(!("_"in document)||!("_e_8vj"in document._)||!(a in document._._e_8vj))&&document.addEventListener(a,sa,c);h||(h=f._={});switch(a){case "DOMContentLoaded":if("complete"==document.readyState)return;f===d&&(f=document);e=l;if(!ga){ga=l;var g=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(g,50);return}M.call(f,{type:a,isTrusted:l,__custom_event:j})};if("createEventObject"in document&&"doScroll"in document.documentElement)try{d.frameElement||g()}catch(i){}}break;
case "load":"tagName"in f&&"SCRIPT"===f.tagName.toUpperCase()&&(e=l,f.onreadystatechange=function(){"loaded"===f.readyState&&(f.onreadystatechange=n,f.attachEvent("onreadystatechange",z.call(M,f,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}f.setInterval&&(f!=d&&!f.frameElement)&&(f=d);b.uuid||(b.uuid=++ra);if(!(c=h._h_9e2))c=h._h_9e2=z.call(M,f);h._e_8vj||(h._e_8vj={});h._e_8vj[a]||(h._e_8vj[a]={},e||f.attachEvent("on"+a,c));h._e_8vj[a][b.uuid]=b}},k.addEventListener.__shim__=
l,k.removeEventListener=m.removeEventListener=d.removeEventListener=document.removeEventListener=function(a,b){var c=this._,f,h,d;if(!("function"!=typeof b||!b.uuid||!c))if(f=c._h_9e2){h=c._e_8vj&&c._e_8vj[a];delete h[b.uuid];for(d in h)if(B(h,d))return;this.detachEvent("on"+a,f);delete c._e_8vj[a];for(d in c._e_8vj)if(B(c._e_8vj,d))return;delete c._e_8vj}},k.removeEventListener.__shim__=l,document.attachEvent("onmousedown",function(){u.b=event.button}),document.attachEvent("onclick",function(){u.b=
j}));document.dispatchEvent||(k.dispatchEvent=m.dispatchEvent=d.dispatchEvent=document.dispatchEvent=function(a){if(!a.type)return l;a.returnValue||(a.returnValue=l);a.cancelBubble&&(a.cancelBubble=q);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===d||-2146827850===b.number&&!(a.bubbles=q)){a.__custom_event=l;for(var c=a.target=this,f="on"+a.type;!a.cancelBubble&&c;)(f in c&&"function"==typeof c[f]&&(a.__dom0__=c[f])||"_"in c&&"_e_8vj"in c._)&&
M.call(c,a),c=a.bubbles?c===document?document.defaultView:c.parentNode:n,"__dom0__"in a&&(a.__dom0__=j);return!a.cancelBubble}C(b)}},k.dispatchEvent.__shim__=l);document.createEvent||(document.createEvent=function(){return new s(document.createEventObject())});g.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),f,d,e,g,i,k,m,p;if(!("INPUT"!=c&&"TEXTAREA"!=c)){k=document.activeElement;b=document.selection;this._&&(m=this._.__stop_events__,this._.__stop_events__=l);k._&&(p=k._.__stop_events__,
k._.__stop_events__=l);try{this.focus(),f=b.createRange(),d=f.duplicate(),"TEXTAREA"==c?(e=this.value,f=d,a?(f.moveEnd("character",e.length),i=""==f.text?e.length:e.lastIndexOf(f.text)):(f.moveStart("character",-e.length),i=f.text.length)):(d.moveToElementText(this),d.setEndPoint("EndToEnd",f),g=d.text.length-f.text.length,i=a?g:g+f.text.length),k&&k.focus&&k.focus()}catch(s){i=j}this._&&!m&&delete this._.__stop_events__;k._&&!p&&delete k._.__stop_events__;return i}}function b(a,b){if(a!=j){b==j&&
(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(l),c.moveStart("character",a),c.moveEnd("character",b-a),c.select())}}var c=d.HTMLTextAreaElement&&d.HTMLTextAreaElement.prototype,f={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,l)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},set:function(c){b.call(this,a.call(this,l),c);return c}}};Object.defineProperties(d.HTMLInputElement&&
d.HTMLInputElement.prototype||p,f);c&&Object.defineProperties(c,f)});D.prototype=[];e=new D;e.push(1);e.length?d.NodeList=D:(e=document.createElement("iframe"),e.style.display="none",(document.body||m).appendChild(e),e.contentWindow.document.write("<script>parent.NodeList=Array;<\/script>"),D=d.NodeList);D.prototype.item=function(a){return this[a]};document.querySelectorAll&&ka();document.doctype===n&&7<P&&g.push(function(){var a=document.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});
Object.defineProperty(document,"doctype",{configurable:l,enumerable:q,get:function(){return a}})});k.contains||(k.contains=pa);y.call(ca,document,"").contains||(d.Text&&d.Text.prototype?g.push(z.call(t,n,Text.prototype,k)):document.createTextNode=function(a){a=y.call(ca,this,a);a.contains=k.contains;return a});!y.call(U,document).contains&&(d.HTMLDocument&&d.HTMLDocument.prototype)&&g.push(z.call(t,n,d.HTMLDocument.prototype,k));"children"in w||g.push(function(){Object.defineProperty(p,"children",
{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});g.push(function(){function a(a,c){var f;try{var d=a;"element"in d&&("defaults"in d&&"document"in d)&&(d=d.element);var e=d.getBoundingClientRect(),g=document.body;f=!m.contains(d)?c?e.left:e.top:c?e.left+K()-(m.clientLeft||g.clientLeft||0):e.top+L()-(m.clientTop||g.clientTop||0)}catch(i){f=a;d=0;for(e=c?"offsetLeft":"offsetTop";f;)d+=parseInt(f[e],10),f=f.offsetParent;f=d}return f}Object.defineProperties(p,
{offsetLeft:{get:function(){return a(this,l)}},offsetTop:{get:function(){return a(this)}}})});w.childElementCount==j&&g.push(function(){Object.defineProperties(p,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=
this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});document.ELEMENT_NODE||(e={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},t(document,e),t(k,e),t(d.Node,e));"textContent"in w||g.push(function(){Object.defineProperty(k,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in
this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in w||(document.isEqualNode=m.isEqualNode=k.isEqualNode=function(a){var b,c;if(a===n||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return q;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return q;b=0;for(c=this.attributes.length;b<c;b++){var d=this.attributes[length],e=a.getAttributeNS(d.namespaceURI,
d.localName);if(e===n||e.value!==d.value)return q}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return q;b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===q)return q;return l});document.importNode||(document.importNode=function(a,b){switch(a.nodeType){case 1:var c=document.createElement(a.nodeName),d=a.attributes,e,g,i;if(d&&0<d.length){g=
0;for(i=d.length;g<i;)d=a.attributes[g++],c.setAttribute(d.nodeName,a.getAttribute(d.nodeName))}if(b&&(e=a.childNodes)&&0<e.length){g=0;for(i=e.length;g<i;)c.appendChild(document.importNode(e[g++],b))}return c;case 3:case 4:case 8:return document.createTextNode(a.nodeValue)}da("NOT_SUPPORTED_ERR");return n},document.importNode.shim=l);e="compareDocumentPosition";e in document||(g=i||"DOCUMENT_POSITION_",m[e]=document[e]=k[e]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=
a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0},i="DISCONNECTED",m[g+i]=document[g+i]=k[g+i]=1,i="PRECEDING",m[g+i]=document[g+i]=k[g+i]=2,i="FOLLOWING",m[g+i]=document[g+i]=k[g+i]=4,i="CONTAINS",m[g+i]=document[g+i]=k[g+i]=8,i="CONTAINED_BY",m[g+i]=document[g+i]=k[g+i]=16);d.getComputedStyle||(d.getComputedStyle=function(a){var b=a.currentStyle||a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=
X.getPropertyValue.bind(a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=function(){da("NO_MODIFICATION_ALLOWED_ERR")},a.runtimeStyle.getPropertyPriority=function(){return""},a.runtimeStyle.item=X.item);var c,f;(f=d.CSSStyleDeclaration)&&(f=f.prototype)&&(!("float"in b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(f,"float"))&&delete f["float"],Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:z.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},
a)}}),c&&Object.defineProperty(f,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(f,"opacity"))&&delete f.opacity,Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:z.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||G.call(this.style)||G.call(this.runtimeStyle)},a)}}),c&&Object.defineProperty(f,"opacity",c))):("float"in b||(a.runtimeStyle["float"]={valueOf:z.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}),"opacity"in
b||(a.runtimeStyle.opacity={valueOf:z.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||G.call(this.style)||G.call(this.runtimeStyle)},a)}));return a.currentStyle});document.createDocumentFragment=function(){var a=y.call(U,this);d.DocumentFragment===d.Document&&t(a,d.DocumentFragment.prototype);return T(a)};i=(w.innerHTML="<x-x></x-x>",1===w.childNodes.length&&1===w.childNodes[0].nodeType);F="|"+F+"|";R.ielt9=l;v=T(y.call(U,document));i||(T(document),document.head.insertAdjacentHTML("beforeend",
"<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>"));0===y.call(O,document,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(I=v.appendChild("createElement"in v&&v.createElement("div")||v.ownerDocument.createElement("div")),ha=8===P?w.cloneNode:8>P?k.cloneNode:j,k.cloneNode=function(a){var b,c;ba.test(this.nodeName)?b=y.call(this.__nativeCloneNode__||ha,this,a):(I.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(this.innerHTML,
""),I.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=I.firstChild,!b&&!a&&((c=c.match(qa))&&(c=c[1]),c&&(v.createElement(c),I.innerHTML=c,b=I.firstChild)));return v.appendChild(b)});var ta=/\s+(?=\S)|^/g,ia=p.getAttribute,ua=p.setAttribute,Z=p.removeAttribute;p.setAttribute=function(a,b){H[a]!==j?a=H[a]:Y[a]===j&&0!==a.indexOf("data-")&&(a=a.toUpperCase());return ua.call(this,a,b+"")};p.getAttribute=function(a){var b,c;if(H[a]!==j)return ia.call(this,H[a]);if(Y[a]===j&&0!==
a.indexOf("data-"))b=a.toUpperCase();else return ia.call(this,a);c=this[b];c||(!(b in this)&&"string"===typeof this[a]?(c=this[b]=this[a],delete this[a]):c=j);return c?c+"":n};p.removeAttribute=function(a){var b,c;if(H[a]!==j)return Z.call(this,H[a]);if(Y[a]===j&&0!==a.indexOf("data-"))b=a.toUpperCase();else return Z.call(this,a);if((c=b in this)||this.getAttribute(a)!==n)Z.call(this,b),delete this[b];return c};e="getElementsByClassName";!p[e]&&document.querySelectorAll&&(p[e]=m[e]=document[e]=function(a){return!a||
!(a=na.call(a))?new D:y.call(this.querySelectorAll||document.querySelectorAll,this,a.replace(ta,"."))});if(e=d.CSSStyleDeclaration)"opacity"in m.style||(Object.defineProperty(e.prototype,"opacity",{get:G,set:function(a){"object"==typeof a&&(a=a.valueOf());this.opacity!==G.call(this)&&delete this.opacity;a=a&&"alpha(opacity="+(0.9999<=a?"100":0>a?0:~~(100*a))+")"||"";this.filter=W.test(this.filter)?this.filter.replace(W,a):this.filter+(" "+a);this.msOpacity=this.opacity}}),Object.defineProperty(e.prototype,
"msOpacity",{value:""})),"float"in m.style||Object.defineProperty(e.prototype,"float",{get:function(){return this.styleFloat},set:function(a){return this.styleFloat=a}}),"getPropertyValue"in e||function(a){for(var b in a)B.call(a,b)&&(this[b]=a[b])}.call(e,X);(function(a,b,c,d){function e(a){for(var b=a.length>>>0,c=new D,d=0;d<b;d++)d in a&&c.push(a[d]);return c}document.querySelectorAll=function(){return e(a.apply(this,arguments))};document.querySelector=function(){return b.apply(this,arguments)};
p.querySelectorAll=function(){return e(c.apply(this,arguments))};p.querySelector=function(){return d.apply(this,arguments)}})(document.querySelectorAll,document.querySelector,p.querySelectorAll,p.querySelector);w=e=x=Q=i=j}})(window,function(d,t){for(var u in t)Object.prototype.hasOwnProperty.call(t,u)&&!Object.prototype.hasOwnProperty.call(d,u)&&(d[u]=t[u]);return d});
})();
