/* ES6/DOM4 polyfill for IE8 | @version 0.7 final | MIT License | github.com/termi */
;(function() {
var f=void 0,g=!0,h=null,k=!1;function l(){return function(){}}var n=window;function q(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&!Object.prototype.hasOwnProperty.call(a,c)&&(a[c]=b[c]);return a}
function s(a){if(!("__isFixed"in a)){var b="button"in a&&a.button;a.__isFixed=g;if("click"===a.type||"dblclick"===a.type)a.detail===f&&(a.detail="click"===a.type?1:2),!a.button&&s.b!==f&&(b=s.b);q(a,t);a.defaultPrevented||(a.defaultPrevented=k);a.target||(a.target=a.srcElement||document);a.relatedTarget===f&&a.fromElement&&(a.relatedTarget=a.fromElement==a.target?a.toElement:a.fromElement);"clientX"in a&&a.pageX==h&&(a.pageX=a.clientX+u()-(v.clientLeft||0),a.pageY=a.clientY+w()-(v.clientTop||0));
!a.which&&b&&(a.which=b&1?1:b&2?3:b&4?2:0);"timeStamp"in a||(a.timeStamp=+new ba);"eventPhase"in a||(a.eventPhase=a.target==this?2:3);"currentTarget"in a||(a.currentTarget=this);a.keyCode||(a.keyCode=a.charCode||a.which);!a.attrName&&a.propertyName&&(a.attrName=ca.call(a.propertyName,".")[0]);return a}}
function y(a){if(s!==f){var b=this._,c,d,e,j;if(!b.__stop_events__){c=[];d=[];j="_e_8vj"+(da?"-":"");if(!b||!b[j])if("__dom0__"in a)b||(b={}),b[j]||(b[j]={});else return;a||(a=window.event);if("__custom_event"in a)e=a;else if(!(e=a.__customEvent__))a.bubbles==f&&(a.bubbles=g),a.cancelable==f&&(a.cancelable=g),e=a.__customEvent__=new z(a),e.initEvent(a.type,a.bubbles,a.cancelable),s.call(this,e),e.g=g,e.__custom_event=f;e.ietl9_event=a;a.currentTarget=this;b=b[j][e.type];"__dom0__"in a&&((b||(b=[]))[0]=
a.__dom0__);if(b){for(var p in b)if(A(b,p)){j=b[p];var m;"object"===typeof j&&(m=j,j=j.handleEvent);try{if(j&&(e.result=B.call(j,m||this,e))===k)e.preventDefault(),e.stopPropagation()}catch(r){c.push(r),d.push(r.message),console&&console.error(r)}if(e.__stopNow)break}b[0]=f;delete b[0];a.returnValue=e.returnValue;a.cancelBubble=e.cancelBubble;1==c.length?C(c[0]):1<c.length&&(d=Error("Multiple errors thrown : "+e.type+" :  : "+d.join("|")),d.errors=c,C(d))}this===document&&(!e.cancelBubble&&3===e.eventPhase)&&
(y.call(this.defaultView,e),a.cancelBubble=g)}}}function D(){}function ea(a){var b=this.__orig__createElement__(a);if(fa.test(a))return b;~E.indexOf("|"+a+"|")||(ga.push(a),E+=a+"|",(G.__orig__createElement__||G.createElement)(a));return G.appendChild(b)}function ha(a){var b=-1;if(a.createElement){for(;++b<ga.length;)a.createElement(ga[b]);a.createElement!==ea&&!("ielt9"in a.createElement)&&(a.__orig__createElement__=a.createElement,a.createElement=ea)}return a}
var H=window.eval&&window.eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||h;
if(9>H){n.Element||((n.Element=window.ActiveXObject).prototype.ie=g);n.HTMLElement||(n.HTMLElement=n.Element);n.Node||(n.Node=n.Element);var ia;n.DocumentFragment||(n.DocumentFragment=n.Document||n.HTMLDocument||(ia=l(),ia.prototype={},ia));n.Document||(n.Document=n.DocumentFragment);n._={ielt9shims:[],orig_:n._};var I=n._.ielt9shims,ja=document.createDocumentFragment,ka=document.createElement,la=document.createTextNode,v=document.documentElement,C=function(a){throw a instanceof Error?a:Error(a);
},ma=function(a){var b=Object.create(DOMException.prototype);b.code=DOMException[a];b.message=a+": DOM Exception "+b.code;throw b;},na=function(a,b){for(var c in b)if(A(b,c)&&a[c]!==b[c])try{a[c]=b[c]}catch(d){}},qa=String.prototype.trim||function(){for(var a=this.replace(oa,""),b=a.length;pa.test(a.charAt(--b)););return a.slice(0,b+1)},ca=String.prototype.split,ra=String.prototype.substr,sa=Array.prototype.slice,J=Function.prototype.apply,B=Function.prototype.call,K=Function.prototype.bind||function(a,
b){var c=this,d=sa.call(arguments,1);return function(){return J.call(c,a,d.concat(sa.call(arguments)))}},L,A=K.call(Function.prototype.call,Object.prototype.hasOwnProperty),N=document.createElement("p"),O=n.Node.prototype,P=n.Element.prototype,ta=N.contains||O.contains,ba=Date,ua=/^\<([\w\:\-]*)[\>\ ]/i,oa=/^\s+/,pa=/\s/,va,Q,R,wa="every filter forEach indexOf join lastIndexOf map reduce reduceRight reverse slice some toString".split(" "),xa,ya=/alpha\(opacity=([^\)]+)\)/,S=function(){var a=(this.filter||
"").match(ya);return a?parseInt(a[1])/100+"":""},za={getPropertyValue:function(a){return this.getAttribute(a)},removeProperty:function(a){this.removeAttribute(a)},setProperty:function(a,b,c){"important"!=c?this.setAttribute(a,b):(c=RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))","i"),a=";"+a+":"+b+" !important;",this.cssText=c.test(this.cssText)?this.cssText.replace(c,a):this.cssText+a)},getPropertyPriority:function(a){return((this.cssText||"").match(RegExp(a+"\\s*:\\s*(\\S+)\\s*(?:[$;]|(?:(!important)\\s*[$;]))",
"i"))||[])[2]||""},item:l()},T={"for":"htmlFor","class":"className",value:"defaultValue"},Aa={action:h,cite:h,codebase:h,data:h,href:h,longdesc:h,lowsrc:h,src:h,usemap:h},U={id:g,value:g,checked:g,disabled:g,ismap:g,multiple:g,readonly:g,selected:g},z,V,t,Ba=1,Ca=l(),da=k,Da,E="abbr|article|aside|audio|canvas|command|datalist|details|figure|figcaption|footer|header|hgroup|keygen|mark|meter|main|nav|output|progress|section|source|summary|time|video",ga=E.split("|"),fa=/^<|^(?:a|b|button|code|div|fieldset|form|map|h1|h2|h3|h4|h5|h6|i|object|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul|optgroup)$/i,
Ea,G,W,Fa,u,w;Q=document.createElement("iframe");Q.style.display="none";(document.body||v).appendChild(Q);Q.contentWindow.document.write("<script>parent._.NodeList=Array;parent._.EMP=Object.prototype\x3c/script>");xa=n._.NodeList;delete n._.NodeList;L=n._.EMP;delete n._.EMP;delete L.constructor;delete L.hasOwnProperty;delete L.propertyIsEnumerable;delete L.isPrototypeOf;delete L.toLocaleString;delete L.toString;delete L.valueOf;L.__proto__=h;I.push(function(){var a=Object.create;Object.create=function(b){b===
h&&(arguments[0]=L);a.apply(this,arguments)}});"CSS1Compat"===document.compatMode?(u=function(){return v.scrollLeft},w=function(){return v.scrollTop}):(u=function(){return document.body.scrollTop},w=function(){return document.body.scrollLeft});document.head||(document.head=document.getElementsByTagName("head")[0]);"defaultView"in document||(document.defaultView=document.parentWindow);Q=k;try{Q=isNaN.apply(h,{})}catch(Ga){}Q||(Function.prototype.apply=function(a,b){return!b?J.call(this,a):"object"!==
typeof b||b instanceof Array||!("length"in b)?J.call(this,a,b):J.call(this,a,Array.from(b))});"b"!=="ab".substr(-1)&&(String.prototype.substr=function(a,b){return ra.call(this,0>a?0>(a=this.length+a)?0:a:a,b)});if("te".split(/(s)*/)[1]!=f||3!="1_1".split(/(_)/).length)va=/()??/.exec("")[1]===f,String.prototype.split=function(a,b){var c=this;if(!(a instanceof RegExp))return a===f&&0===b?[]:ca.call(c,a,b);var d=[],e=(a.ignoreCase?"i":"")+(a.multiline?"m":"")+(a.extended?"x":"")+(a.sticky?"y":""),j=
0,p,m,r;a=RegExp(a.source,e+"g");c+="";va||(p=RegExp("^"+a.source+"$(?!\\s)",e));b=b===f?4294967295:b>>>0;if(!b)return[];for(;m=a.exec(c);){e=m.index+m[0].length;if(e>j&&(d.push(c.slice(j,m.index)),!va&&1<m.length&&m[0].replace(p,function(){for(var a=1,b=arguments.length-2;a<b;a++)arguments[a]===f&&(m[a]=f)}),1<m.length&&m.index<c.length&&d.push.apply(d,m.slice(1)),r=m[0].length,j=e,d.length>=b))break;a.lastIndex===m.index&&a.lastIndex++}j===c.length?(r||!a.test(""))&&d.push(""):d.push(c.slice(j));
return d.length>b?d.slice(0,b):d};n.DOMException||(Q=(n.DOMException=l()).prototype=Error(),Q.INDEX_SIZE_ERR=1,Q.HIERARCHY_REQUEST_ERR=3,Q.WRONG_DOCUMENT_ERR=4,Q.INVALID_CHARACTER_ERR=5,Q.NO_MODIFICATION_ALLOWED_ERR=7,Q.NOT_FOUND_ERR=8,Q.NOT_SUPPORTED_ERR=9,Q.INVALID_STATE_ERR=11,Q.SYNTAX_ERR=12,Q.INVALID_MODIFICATION_ERR=13,Q.NAMESPACE_ERR=14,Q.INVALID_ACCESS_ERR=15);"pageXOffset"in n||I.push(function(){Object.defineProperty(n,"pageXOffset",{get:u});Object.defineProperty(n,"pageYOffset",{get:w})});
R=n.Event=function(){C("")};V={initEvent:function(a,b,c){(a==f||b==f||c==f)&&C("WRONG_ARGUMENTS_ERR");this.type=a;this.bubbles=b;this.cancelable=c;this.g=k;this.target=h;this.timeStamp||(this.timeStamp=+new ba)},initCustomEvent:function(a,b,c,d){V.initEvent.call(this,a,b,c);this.detail=d},initUIEvent:function(a,b,c,d,e){V.initCustomEvent.call(this,a,b,c,e);this.view=d},initMouseEvent:function(a,b,c,d,e,j,p,m,r,F,Y,M,x,$,aa){V.initUIEvent.call(this,a,b,c,d,e);this.screenX=j;this.screenY=p;this.clientX=
m;this.clientY=r;this.ctrlKey=F;this.altKey=Y;this.shiftKey=M;this.metaKey=x;this.button=$;this.relatedTarget=aa}};t=R.prototype={constructor:R,preventDefault:function(){this.cancelable!==k&&(z.a.call(this).returnValue=this.returnValue=k,z.d.call(this),this.defaultPrevented=g)},stopPropagation:function(){z.a.call(this).cancelBubble=this.cancelBubble=g;z.d.call(this)}};t.stopImmediatePropagation=function(){this.__stopNow=g;this.stopPropagation()};t.defaultPrevented=k;for(Q in V)A(V,Q)&&(t[Q]=function(){V[arguments.callee.name].apply(this,
arguments);na(this.ietl9_event,this)},t[Q].name=Q);z=function(a){this.ietl9_event=a;a.returnValue=g;na(this,a)};z.a=function(){var a=this.ietl9_event;a===f?C("WRONG_THIS_ERR"):a===h&&(a=z.a.f);return a};z.a.f={};z.d=function(){this.ietl9_event&&(this.ietl9_event=h)};R=l();R.prototype=t;R=new R;R.constructor=z;z.prototype=R;N.addEventListener||((n.Text&&n.Text.prototype||O).addEventListener=O.addEventListener=v.addEventListener=n.addEventListener=document.addEventListener=function(a,b,c){if("function"==
typeof b||"object"===typeof b&&b.handleEvent){var d=this,e=d._,j=k;d==n&&(!("_"in document)||!("_e_8vj"in document._)||!(a in document._._e_8vj))&&document.addEventListener(a,Ca,c);e||(e=d._={});switch(a){case "DOMContentLoaded":if("complete"==document.readyState)return;d===n&&(d=document);j=g;if(!Da){Da=g;var p=function(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(p,50);return}y.call(d,{type:a,isTrusted:g,__custom_event:f})};if("createEventObject"in document&&"doScroll"in document.documentElement)try{n.frameElement||
p()}catch(m){}}break;case "load":"tagName"in d&&"SCRIPT"===d.tagName.toUpperCase()&&(j=g,d.onreadystatechange=function(){"loaded"===d.readyState&&(d.onreadystatechange=h,d.attachEvent("onreadystatechange",K.call(y,d,{type:a})))},a="readystatechange");break;case "DOMMouseScroll":a="mousewheel"}d.setInterval&&(d!=n&&!d.frameElement)&&(d=n);b.uuid||(b.uuid=++Ba);if(!(c=e._h_9e2))c=e._h_9e2=K.call(y,d);e._e_8vj||(e._e_8vj={});e._e_8vj[a]||(e._e_8vj[a]={},j||d.attachEvent("on"+a,c));e._e_8vj[a][b.uuid]=
b}},O.addEventListener.__shim__=g,O.removeEventListener=v.removeEventListener=n.removeEventListener=document.removeEventListener=function(a,b){var c=this._,d,e;if(!("function"!=typeof b&&!("object"===typeof b&&b.handleEvent)||!b.uuid||!c))if(d=c._h_9e2){e=c._e_8vj&&c._e_8vj[a];delete e[b.uuid];for(any in e)if(A(e,any))return;this.detachEvent("on"+a,d);delete c._e_8vj[a];for(any in c._e_8vj)if(A(c._e_8vj,any))return;delete c._e_8vj}},O.removeEventListener.__shim__=g,document.attachEvent("onmousedown",
function(){s.b=event.button}),document.attachEvent("onclick",function(){s.b=f}));document.dispatchEvent||(O.dispatchEvent=v.dispatchEvent=n.dispatchEvent=document.dispatchEvent=function(a){if(!a.type)return g;a.returnValue||(a.returnValue=g);a.cancelBubble&&(a.cancelBubble=k);delete a.__stopNow;try{return this.fireEvent("on"+a.type,a)}catch(b){if(-2147024809===b.number||this===n||-2146827850===b.number&&!(a.bubbles=k)){a.__custom_event=g;for(var c=a.target=this,d="on"+a.type;!a.cancelBubble&&c;)(d in
c&&"function"==typeof c[d]&&(a.__dom0__=c[d])||"_"in c&&"_e_8vj"in c._)&&y.call(c,a),c=a.bubbles?c===document?document.defaultView:c.parentNode:h,"__dom0__"in a&&(a.__dom0__=f);return!a.cancelBubble}C(b)}},O.dispatchEvent.__shim__=g);document.createEvent||(document.createEvent=function(){return new z(document.createEventObject())});I.push(function(){function a(a){var b,c=this.nodeName.toUpperCase(),d,r,F,Y,M,x,$,aa;if(!("INPUT"!=c&&"TEXTAREA"!=c)){"unknown"!=typeof document.activeElement&&(x=document.activeElement);
b=document.selection;this._&&($=this._.__stop_events__,this._.__stop_events__=g);x&&x._&&(aa=x._.__stop_events__,x._.__stop_events__=g);try{this.focus(),d=b.createRange(),r=d.duplicate(),"TEXTAREA"==c?(F=this.value,d=r,a?(d.moveEnd("character",F.length),M=""==d.text?F.length:F.lastIndexOf(d.text)):(d.moveStart("character",-F.length),M=d.text.length)):(r.moveToElementText(this),r.setEndPoint("EndToEnd",d),Y=r.text.length-d.text.length,M=a?Y:Y+d.text.length),x&&x.focus&&x.focus()}catch(Sa){M=f}this._&&
!$&&delete this._.__stop_events__;x&&(x._&&!aa)&&delete x._.__stop_events__;return M}}function b(a,b){if(a!=f){b==f&&(b=a);var c=this.nodeName.toUpperCase();"INPUT"!=c&&"TEXTAREA"!=c||(c=this.createTextRange(),c.collapse(g),c.moveStart("character",a),c.moveEnd("character",b-a),c.select())}}var c=n.HTMLTextAreaElement&&n.HTMLTextAreaElement.prototype,d={setSelectionRange:{value:b},selectionStart:{get:function(){return a.call(this,g)},set:function(c){b.call(this,c,a.call(this));return c}},selectionEnd:{get:function(){return a.call(this)},
set:function(c){b.call(this,a.call(this,g),c);return c}}};Object.defineProperties(n.HTMLInputElement&&n.HTMLInputElement.prototype||P,d);c&&Object.defineProperties(c,d)});D.prototype=[];Q=new D;Q.push(1);Q.length?(n.NodeList=D,xa=h):D=n.NodeList=xa;D.prototype.item=function(a){return this[a]};if(document.querySelectorAll){var Ha=document.querySelectorAll("#z").constructor.prototype;if(Ha&&Ha!==Array.prototype)for(var Ia in wa)A(Ia,wa)&&(Ha[Ia]||(Ha[Ia]=function(){return J.call(Array.prototype[Ia],
Array.from(this),arguments)}))}document.doctype===h&&7<H&&I.push(function(){var a=document.childNodes[0];Object.defineProperty(a,"nodeType",{get:function(){return 10}});Object.defineProperty(document,"doctype",{configurable:g,enumerable:k,get:function(){return a}})});O.contains||(O.contains=ta);B.call(la,document,"").contains||(n.Text&&n.Text.prototype?I.push(K.call(q,h,Text.prototype,O)):document.createTextNode=function(a){a=B.call(la,this,a);a.contains=O.contains;return a});!B.call(ja,document).contains&&
(n.HTMLDocument&&n.HTMLDocument.prototype)&&I.push(K.call(q,h,n.HTMLDocument.prototype,O));"children"in N||I.push(function(){Object.defineProperty(P,"children",{get:function(){for(var a=[],b=this.firstChild;b;)1==b.nodeType&&a.push(b),b=b.nextSibling;return a}})});I.push(function(){function a(a,c){var d;try{a:{var e=a;"element"in e&&("defaults"in e&&"document"in e)&&(e=e.element);var j=e.getBoundingClientRect(),p,m,r;if((r=e.ownerDocument)!==document){if(p=r&&r.body,m=r&&r.documentElement,!p||!m){d=
c?j.left:j.top;break a}}else p=document.body,m=v;d=c?j.left+u()-(m.clientLeft||p.clientLeft||0):j.top+w()-(m.clientTop||p.clientTop||0)}}catch(F){d=a;e=0;for(j=c?"offsetLeft":"offsetTop";d;)e+=parseInt(d[j],10),d=d.offsetParent;d=e}return d}Object.defineProperties(P,{offsetLeft:{get:function(){return a(this,g)}},offsetTop:{get:function(){return a(this)}}})});N.childElementCount==f&&I.push(function(){Object.defineProperties(P,{firstElementChild:{get:function(){var a;for(a=this.firstChild;a&&1!=a.nodeType;)a=
a.nextSibling;return a}},lastElementChild:{get:function(){var a;for(a=this.lastChild;a&&1!=a.nodeType;)a=a.previousSibling;return a}},nextElementSibling:{get:function(){for(var a=this;(a=a.nextSibling)&&1!=a.nodeType;);return a}},previousElementSibling:{get:function(){for(var a=this;(a=a.previousSibling)&&1!=a.nodeType;);return a}}})});document.ELEMENT_NODE||(Q={ELEMENT_NODE:1,TEXT_NODE:3,PROCESSING_INSTRUCTION_NODE:7,COMMENT_NODE:8,DOCUMENT_NODE:9,DOCUMENT_TYPE_NODE:10,DOCUMENT_FRAGMENT_NODE:11},
q(document,Q),q(O,Q),q(n.Node,Q));"textContent"in N||I.push(function(){Object.defineProperty(O,"textContent",{get:function(){if("innerText"in this)return this.innerText;if("data"in this&&this.appendData)return this.data},set:function(a){"innerText"in this?this.innerText=a:"data"in this&&this.replaceData&&this.replaceData(0,this.length,a);return a}})});"isEqualNode"in N||(document.isEqualNode=v.isEqualNode=O.isEqualNode=function(a){var b,c;if(a===h||a.nodeType!==this.nodeType||10===a.nodeType&&(this.name!==
a.name||this.publicId!==a.publicId||this.systemId!==a.systemId))return k;if(1===a.nodeType){if(this.namespaceURI!=a.namespaceURI||this.prefix!=a.prefix||this.localName!=a.localName)return k;b=0;for(c=this.attributes.length;b<c;b++){var d=this.attributes[length],e=a.getAttributeNS(d.namespaceURI,d.localName);if(e===h||e.value!==d.value)return k}}if(7===a.nodeType&&(this.target!==a.target||this.data!==a.data)||(3===a.nodeType||8===a.nodeType)&&this.data!==a.data||a.childNodes.length!==this.childNodes.length)return k;
b=0;for(c=a.childNodes.length;b<c;b++)if(a.childNodes[b].isEqualNode(this.childNodes[b])===k)return k;return g});document.importNode||(document.importNode=function(a,b){switch(a.nodeType){case 1:var c=document.createElement(a.nodeName),d=a.attributes,e,j,p;if(d&&0<d.length){j=0;for(p=d.length;j<p;)d=a.attributes[j++],c.setAttribute(d.nodeName,a.getAttribute(d.nodeName))}if(b&&(e=a.childNodes)&&0<e.length){j=0;for(p=e.length;j<p;)c.appendChild(document.importNode(e[j++],b))}return c;case 3:case 4:case 8:return document.createTextNode(a.nodeValue)}ma("NOT_SUPPORTED_ERR");
return h},document.importNode.shim=g);Q="compareDocumentPosition";if(!(Q in document)){var X,Z=X||"DOCUMENT_POSITION_";v[Q]=document[Q]=O[Q]=function(a){return this.contains?(this!=a&&this.contains(a)&&16)+(this!=a&&a.contains(this)&&8)+(0<=this.sourceIndex&&0<=a.sourceIndex?(this.sourceIndex<a.sourceIndex&&4)+(this.sourceIndex>a.sourceIndex&&2):1)+0:0};X="DISCONNECTED";v[Z+X]=document[Z+X]=O[Z+X]=1;X="PRECEDING";v[Z+X]=document[Z+X]=O[Z+X]=2;X="FOLLOWING";v[Z+X]=document[Z+X]=O[Z+X]=4;X="CONTAINS";
v[Z+X]=document[Z+X]=O[Z+X]=8;X="CONTAINED_BY";v[Z+X]=document[Z+X]=O[Z+X]=16}n.getComputedStyle||(n.getComputedStyle=function(a){var b=a.currentStyle||a.runtimeStyle;"getPropertyValue"in b||(a.runtimeStyle.getPropertyValue=za.getPropertyValue.bind(a),a.runtimeStyle.setProperty=a.runtimeStyle.removeProperty=function(){ma("NO_MODIFICATION_ALLOWED_ERR")},a.runtimeStyle.getPropertyPriority=function(){return""},a.runtimeStyle.item=za.item);var c,d;(d=n.CSSStyleDeclaration)&&(d=d.prototype)&&(!("float"in
b)||!("opacity"in b))?("float"in b||((c=Object.getOwnPropertyDescriptor(d,"float"))&&delete d["float"],Object.defineProperty(a.runtimeStyle,"float",{value:{valueOf:K.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}}),c&&Object.defineProperty(d,"float",c)),"opacity"in b||((c=Object.getOwnPropertyDescriptor(d,"opacity"))&&delete d.opacity,Object.defineProperty(a.runtimeStyle,"opacity",{value:{valueOf:K.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||
S.call(this.style)||S.call(this.runtimeStyle)},a)}}),c&&Object.defineProperty(d,"opacity",c))):("float"in b||(a.runtimeStyle["float"]={valueOf:K.call(function(){return this.runtimeStyle.styleFloat||this.style.styleFloat},a)}),"opacity"in b||(a.runtimeStyle.opacity={valueOf:K.call(function(){return this.runtimeStyle.msOpacity||this.style.msOpacity||S.call(this.style)||S.call(this.runtimeStyle)},a)}));return a.currentStyle});document.createDocumentFragment=function(){var a=B.call(ja,this);n.DocumentFragment===
n.Document&&q(a,n.DocumentFragment.prototype);return ha(a)};Ea=(N.innerHTML="<x-x></x-x>",1===N.childNodes.length&&1===N.childNodes[0].nodeType);E="|"+E+"|";ea.ielt9=g;G=ha(B.call(ja,document));Ea||(ha(document),document.head.insertAdjacentHTML("beforeend","<br><style>article,aside,figcaption,figure,footer,header,hgroup,nav,section{display:block}mark{background:#FF0;color:#000}</style>"));0===B.call(ka,document,"x-x").cloneNode().outerHTML.indexOf("<:x-x>")&&(W=G.appendChild("createElement"in G&&
G.createElement("div")||G.ownerDocument.createElement("div")),Fa=8===H?N.cloneNode:8>H?O.cloneNode:f,O.cloneNode=function(a){var b,c;fa.test(this.nodeName)?b=B.call(this.__nativeCloneNode__||Fa,this,a):(W.innerHTML="",c=a?this.outerHTML:this.outerHTML.replace(/<(\w+)([^>]*)>[\W\w]*$/,"<$1$2></$1>"),W.innerHTML=c.replace(/^\<\:/,"<").replace(/\<\/\:([\w\-]*\>)$/,"<$1"),b=W.firstChild,!b&&!a&&((c=c.match(ua))&&(c=c[1]),c&&(G.createElement(c),W.innerHTML=c,b=W.firstChild)));return G.appendChild(b)});
var Ja=/\s+(?=\S)|^/g,Ka=P.getAttribute,La=P.setAttribute,Ma=P.removeAttribute;U.e={};U.c=function(a,b){if(b in this)return this[b];var c=a.nodeName;if(!(a=U.e[c]))a=U.e[c]=ka(c);c=Ka.call(a,b)!==h;c||(c=(c=a.constructor)&&(c=c.prototype)&&(c=Object.getOwnPropertyDescriptor(c,b))&&/\[native\scode\]/.test(c.get+""));return this[b]=c};P.setAttribute=function(a,b){var c=a.toLowerCase();T[c]!==f?a=T[c]:Aa[c]===f&&(0!==c.indexOf("data-")&&!U.c(this,c))&&(a=a.toUpperCase());return La.call(this,a,b+"")};
P.getAttribute=function(a){var b;b=a.toLowerCase();var c;if(T[b]!==f)return Ka.call(this,T[b]);if(Aa[b]!==f)return(c=this.attributes)&&(c=c[b])&&(c=c.nodeValue)&&c+""||h;if(0!==b.indexOf("data-")&&!U.c(this,b))b=a.toUpperCase();else return Ka.call(this,a);c=this[b];c||(!(b in this)&&"string"===typeof this[a]?(c=this[b]=this[a],delete this[a]):c=f);return c!==f?c+"":h};P.removeAttribute=function(a){var b;b=a.toLowerCase();var c;if(T[b]!==f)return Ma.call(this,T[b]);if(Aa[b]===f&&0!==b.indexOf("data-")&&
!U.c(this,b))b=a.toUpperCase();else return Ma.call(this,a);if((c=b in this)||this.getAttribute(a)!==h)Ma.call(this,b),delete this[b];return c};Q="getElementsByClassName";!P[Q]&&document.querySelectorAll&&(P[Q]=v[Q]=document[Q]=function(a){return!a||!(a=qa.call(a))?new D:B.call(this.querySelectorAll||document.querySelectorAll,this,a.replace(Ja,"."))});if(Q=n.CSSStyleDeclaration)"opacity"in v.style||(Object.defineProperty(Q.prototype,"opacity",{get:S,set:function(a){"object"==typeof a&&(a=a.valueOf());
this.opacity!==S.call(this)&&delete this.opacity;a=a&&"alpha(opacity="+(0.9999<=a?"100":0>a?0:~~(100*a))+")"||"";this.filter=ya.test(this.filter)?this.filter.replace(ya,a):this.filter+(" "+a);this.msOpacity=this.opacity}}),Object.defineProperty(Q.prototype,"msOpacity",{value:""})),"float"in v.style||Object.defineProperty(Q.prototype,"float",{get:function(){return this.styleFloat},set:function(a){return this.styleFloat=a}}),"getPropertyValue"in Q||function(a){for(var b in a)A.call(a,b)&&(this[b]=a[b])}.call(Q,
za);if(Q=n.TextRectangle)Object.defineProperty(Q,"width",{get:function(){return this.right-this.left}}),Object.defineProperty(Q,"height",{get:function(){return this.bottom-this.top}});var Na=document.querySelectorAll,Oa=document.querySelector,Pa=P.querySelectorAll,Qa=P.querySelector,Ra=function(a){for(var b=a.length>>>0,c=new D,d=0;d<b;d++)d in a&&c.push(a[d]);return c};document.querySelectorAll=function(){return Ra(Na.apply(this,arguments))};document.querySelector=function(){return Oa.apply(this,
arguments)};P.querySelectorAll=function(){return Ra(Pa.apply(this,arguments))};P.querySelector=function(){return Qa.apply(this,arguments)};N=Q=R=wa=Ea=h}
})();
