/* Copyright 2011-2012, Dmitriy Pakhtinov ( spb.piksel@gmail.com ) and github.com/termi */
;(function() {"use strict";
var b=null,e=window,f=e.JSON||{},i=Function.prototype.bind||!1,j=i.call(Function.prototype.call,Object.prototype.hasOwnProperty),k=e.history||{},l=e.location,m="pushState"in k,n=m&&void 0===k.state,p=l.href,r=k.pushState,s=k.replaceState,t=f.parse,u=f.stringify,v=e.sessionStorage,w=0,x=/[^\/]+$/g,y=location.pathname.split("#")[0].split("?")[0],z,A=document.createElement("a"),B,C,E,F,G,H,I,J=/^[^#]*/,K=/^#[\/]?(?:\/)?/,L=/^(?:[a-z]+\:)?\/\//;
z=function(a,c){if(a){if(!m)var d=z(),g=d.d,h=d.h,o=a.charAt(0),a=L.test(a)?"/"==o?h+a:a:h+"//"+d.g+("/"==o?a:"?"==o?g+a:"#"==o?g+d.e+a:g.replace(x,"")+a)}else if(a=l.href,!m||c)a=l.protocol+"//"+l.host+(-1!=a.indexOf("#")?"/":y)+a.replace(J,"").replace(K,"");if(B!==a){A.href=B=a;H=A.port;G=A.host;I=A.pathname;if("http:"===A.protocol&&80==H||"https:"===A.protocol&&443==H)G=A.hostname,H="";I="/"==I.charAt(0)?I:"/"+I;C=I+A.search+A.hash;F=I+A.search;E=F+A.hash}return{a:A.protocol+"//"+G+C,h:A.protocol,
g:G,i:A.hostname||l.hostname,j:H||l.port,d:I,e:A.search,f:A.hash,b:C,c:F,k:E}};var M=k||!1,O={get:function(){return N()[M.location.href]||b}},Q={set:function(a){e.location=a},get:function(){return m?l:P}},P={assign:function(a){l.assign(m||0!==a.indexOf("#")?a:"#"+z().c+a)},reload:l.reload,replace:function(a){l.replace(m||0!==a.indexOf("#")?a:"#"+z().c+a)},toString:function(){return this.href}};
function R(a,c,d){try{if(Object.defineProperty.ielt8)throw Error;Object.defineProperties(a,c)}catch(g){if(a.__defineGetter__)for(var h in c)j(c,h)&&(a.__defineGetter__(h,c[h].get),c[h].set&&a.__defineSetter__(h,c[h].set));if(d)return!1}return a}function N(a){return v?a?v.setItem("__hitoryapi__",u(a)):t(v.getItem("__hitoryapi__"))||{}:{}}
function S(a,c,d){var g=new Event(2==a?"hashchange":"popstate");g.oldUrl=c||"";g.newUrl=d||"";g.__history_shim__=!0;if(!m&&2!=a&&e.onpopstate)e.onpopstate(g);e.dispatchEvent(g)}function T(a){p===l.href&&(a.stopImmediatePropagation(),p=0);e.removeEventListener("popstate",T)}var U=e.onpopstate||b,V=e.onhashchange||b,W=0,X=z(),Y=/^.*?(#|$)/,Z=X.a;
e.addEventListener("hashchange",function(a){if(!a.__history_shim__){var c=z();if(w)return Z=c.a,w=0;var d=a.oldURL||Z,a=Z=a.newURL||c.a,c=d.replace(Y,""),g=a.replace(Y,"");d!=a&&!W&&S(void 0,d,a);p=W=0;c!=g&&S(2,d,a)}});e.addEventListener("popstate",T);e.addEventListener("popstate",function(){p=0;W=1});M=R(M,void 0===k.state?{state:O,location:Q}:{location:Q});
P=R(P,{href:{set:function(a){l.href=a},get:function(){return z().a}},protocol:{set:function(a){l.protocol=a},get:function(){return l.protocol}},host:{set:function(a){l.host=a},get:function(){return l.host}},hostname:{set:function(a){l.hostname=a},get:function(){return l.hostname}},port:{set:function(a){l.port=a},get:function(){return l.port}},pathname:{set:function(a){l.pathname=a},get:function(){return z().d}},search:{set:function(a){l.search=a},get:function(){return z().e}},hash:{set:function(a){var a=
0===a.indexOf("#")?a:"#"+a,c=z();l.hash="#"+c.c+a},get:function(){return z().f}},origin:{}});"onpopstate"in e||R(e,{onhashchange:{get:function(){return V},set:function(a){V=a||b}},onpopstate:{get:function(){return U},set:function(a){if(U=a||b)if(!m&&p&&!(p=0)&&X.b!==y)clearInterval(b),setTimeout(i.call(S),10)}}},!0);
M.pushState=function(a,c,d,g){var h=N(),o=z(),D=o.a,q=d&&z(d);p=0;d=q?q.a:D;g&&h[D]&&delete h[D];if((!m||n)&&v&&a)h[d]=a,N(h),a=b;r&&s?g?s.call(M,a,c,d):r.call(M,a,c,d):q&&q.b!=o.b&&(w=1,g?l.replace("#/"+q.b):l.hash="/"+q.b)};M.replaceState=function(a,c,d){M.pushState(a,c,d,1)};e.history.emulate=!m;
})();
