/* Microdata API for IE < 8 polyfill | @version 6.1 | MIT License | github.com/termi */
void function(j){
var e=null;
(function(i){if(!("getItems"in document)&&9>(window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||void 0)){var g,k;if((g=window.Node)&&(g=g.prototype)&&g.ielt8)g=document.getElementById("ielt8_style_prev_for_behaviour"),k="",g&&(k=g.getAttribute("data-url")||"",g.id=""),k+=' url("/microdata-js.ielt8.htc") ',g="<style id='ielt8_style_prev_for_behaviour' data-url='"+k+"'>*{behavior: "+k+"}</style>","complete"==document.readyState?document.head.insertAdjacentHTML("beforeend","<br>"+
g):document.write(g);var m,n={INPUT:e,TEXTAREA:e,PROGRESS:e,METER:e,SELECT:e,OUTPUT:e},p={AUDIO:e,EMBED:e,IFRAME:e,IMG:e,SOURCE:e,TRACK:e,VIDEO:e},q={A:e,AREA:e,LINK:e},l=function(a,b){a._||(a._={});var c=a.getAttribute(b,1),d=a._._mcrdt_||(a._._mcrdt_={}),h=d[b];h?c!==e&&h+""!==c&&h.contains("fake"):h=d[b]=new m(function(){return a.getAttribute(b,1)},function(){a.setAttribute(b,this+"",1)},a);return h};g=(HTMLDocument||{}).prototype||{};m=i.DOMStringCollection;var f=function(){this.length=0;this.values=
[]};f.prototype._push=function(a,b){this[this.length++]=a;this.values.push(b)};f.prototype.getValues=function(){for(var a=[],b=-1,c;c=this[++b];)a.push(c.itemValue);return a};f.prototype.toString=function(){return"[object PropertyNodeList]"};var j=function(){this.length=0;this.names=[]};j.prototype.a=function(){for(var a in this)if(this[a]instanceof f||!isNaN(a))this[a]=e,delete this[a];this.length=0;this.names=[]};j.prototype._push=function(a){var b=a.itemValue,c=a.itemProp,d,h=-1;if(c)for(this[this.length++]=
a;d=c[++h];)~this.names.indexOf(d)||this.names.push(d),(this[d]||(this[d]=new f))._push(a,b)};j.prototype.namedItem=function(a){return this[a]instanceof f?this[a]:new f};j.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};j.prototype.item=f.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||e};var r=function(a){var b,c=-1,d;if(void 0!==a.length){for(b={items:[]};d=a[++c];)d.getAttribute("itemscope",1)!==e&&b.items.push(r(d));return b}if(a.getAttribute("itemscope",1)!==
e){b={};if(c=a.getAttribute("itemid",1))b.id=c;if(c=a.getAttribute("itemtype",1))b.type=c;b.properties=a.properties.toJSON()}return b};f.prototype.toJSON=function(){return this.c().map(function(a){a instanceof Element&&(a=r(a));return a})};j.prototype.toJSON=function(){for(var a={},b=this.names,c=-1,d;d=b[++c];)this[d]instanceof f&&(a[d]=this[d].toJSON());return a};_similar_Object_defineProperties_=function(a,b){var c,d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(c=b[d],"get"in c&&(a["get"+
d]=c.get),"set"in c&&(a["set"+d]=c.set))};_similar_Object_defineProperties_(i.Element.prototype,{itemValue:{get:function(){var a=this.nodeName;return this.getAttribute("itemscope")!==e?this:this.getAttribute("itemprop")===e?e:a in n?this.value:"META"===a?this.content:a in p?this.src:a in q?this.href:"OBJECT"===a?this.data:"TIME"===a&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:this.innerText},set:function(a){var b=this.nodeName;if(this.getAttribute("itemprop")===
e)throw a=Object.create(DOMException.prototype),a.code=DOMException.INVALID_ACCESS_ERR,a.message="INVALID_ACCESS_ERR: DOM Exception "+a.code,a;return this[b in n?"value":"META"===b?"content":b in p?"src":b in q?"href":"OBJECT"===b?"data":"TIME"===b&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=a}},itemProp:{get:function(){return l(this,"itemprop")},set:function(a){return this.setAttribute("itemprop",a+"",1),a}},itemScope:{get:function(){return this.getAttribute("itemscope",1)!==e},set:function(a){a?
this.setAttribute("itemscope","",1):this.removeAttribute("itemscope",1);return a}},itemId:{get:function(){var a=(this.getAttribute("itemid",1)||"").trim();a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+"",1),a}},itemType:{get:function(){return l(this,"itemtype")},set:function(a){return this.setAttribute("itemtype",a+""),a}},itemRef:{get:function(){return l(this,"itemref")},set:function(a){return this.setAttribute("itemref",
a+"",1),a}},properties:{get:function(){this._||(this._={});var a=this._._mcrdt_||(this._._mcrdt_={}),b=a.b;if(b)if(i.microdata_liveProperties)b.a();else return b;else b=a.b=new j;for(var c=[],a=[],d=[],h,g=-1,f;f=this.childNodes[++g];)1===f.nodeType&&c.push(f);this.getAttribute("itemref",1)&&(d=this.getAttribute("itemref",1).trim().split(/\s+/),d.forEach(function(a){(a=document.getElementById(a))&&c.push(a)}));c=c.filter(function(a,b){var f=e,g=a,h=[];if(c.indexOf(a)!==b&&-1!==c.indexOf(a,b))return!1;
if(a.id&&-1!==d.indexOf(a.id))return!0;for(;(g=g.parentNode)!==e&&1===g.nodeType;)if(h.push(g),g.getAttribute("itemscope",1)!==e){f=g;break}return f!==e?-1!==c.indexOf(f)?!1:!h.some(function(a){var b=-1,d=e;if(-1!==(b=c.indexOf(a))){for(a=c[b];(a=a.parentNode)!==e&&1===a.nodeType;)if(a.getAttribute("itemscope",1)!==e){d=a;break}if(d===f)return!0}return!1}):!0});for(c.sort(function(a,b){return 3-(b.compareDocumentPosition(a)&6)});h=c.pop();)if(h.getAttribute("itemprop",1)&&a.push(h),h.getAttribute("itemscope",
1)===e)for(g=h.childNodes.length;f=h.childNodes[--g];)1===f.nodeType&&c.push(f);a.forEach(b._push.bind(b));return b}}});g.getItems=document.getItems=function(a){for(var b=this.querySelectorAll("[itemscope]"),c=[],a=(a||"").trim().split(/\s+/),d,g=-1;d=b[++g];){var f=d.getAttribute("itemtype")||"",j=f.split(/\s+/),i,f=!(f&&!d.getAttribute("itemprop",1)&&(!("itemScope"in d)||d.itemScope));for(;!f&&(i=j.pop());)(f=~a.indexOf(i))&&c.push(d)}};i.PropertyNodeList||(i.PropertyNodeList=f);i.HTMLPropertiesCollection||
(i.HTMLPropertiesCollection=j)}})(window);
}(window);
