/* Microdata API for IE < 8 polyfill | @version 6.1 | MIT License | github.com/termi */
void function(j){
var d=null;
(function(j){if(!("getItems"in document)&&9>(window.eval&&eval("/*@cc_on 1;@*/")&&+((/msie (\d+)/i.exec(navigator.userAgent)||[])[1]||0)||void 0)){var f,k;if((f=window.Node)&&(f=f.prototype)&&f.ielt8)f=document.getElementById("ielt8_style_prev_for_behaviour"),k="",f&&(k=f.getAttribute("data-url")||"",f.id=""),k+=' url("/microdata-js.ielt8.htc") ',f="<style id='ielt8_style_prev_for_behaviour' data-url='"+k+"'>*{behavior: "+k+"}</style>","complete"==document.readyState?document.head.insertAdjacentHTML("beforeend","<br>"+
f):document.write(f);var m,n={INPUT:d,TEXTAREA:d,PROGRESS:d,METER:d,SELECT:d,OUTPUT:d},p={AUDIO:d,EMBED:d,IFRAME:d,IMG:d,SOURCE:d,TRACK:d,VIDEO:d},q={A:d,AREA:d,LINK:d},l=function(a,b){a._||(a._={});var c=a.getAttribute(b,1),e=a._._mcrdt_||(a._._mcrdt_={}),h=e[b];h?c!==d&&h+""!==c&&h.contains("fake"):h=e[b]=new m(function(){return a.getAttribute(b,1)},function(){a.setAttribute(b,this+"",1)},a);return h};f=(HTMLDocument||{}).prototype||{};m=j.DOMStringCollection;var g=function(){this.length=0;this.values=
[]};g.prototype._push=function(a,b){this[this.length++]=a;this.values.push(b)};g.prototype.getValues=function(){for(var a=[],b=-1,c;c=this[++b];)a.push(c.itemValue);return a};g.prototype.toString=function(){return"[object PropertyNodeList]"};var i=function(){this.length=0;this.names=[]};i.prototype.a=function(){for(var a in this)if(this[a]instanceof g||!isNaN(a))this[a]=d,delete this[a];this.length=0;this.names=[]};i.prototype._push=function(a){var b=a.itemValue,c=a.itemProp,e,h=-1;if(c)for(this[this.length++]=
a;e=c[++h];)~this.names.indexOf(e)||this.names.push(e),(this[e]||(this[e]=new g))._push(a,b)};i.prototype.namedItem=function(a){return this[a]instanceof g?this[a]:new g};i.prototype.toString=function(){return"[object HTMLPropertiesCollection]"};i.prototype.item=g.prototype.item=function(a){isNaN(a)&&(a=0);return this[a]||d};var r=function(a){var b,c=-1,e;if(void 0!==a.length){for(b={items:[]};e=a[++c];)e.getAttribute("itemscope",1)!==d&&b.items.push(r(e));return b}if(a.getAttribute("itemscope",1)!==
d){b={};if(c=a.getAttribute("itemid",1))b.id=c;if(c=a.getAttribute("itemtype",1))b.type=c;b.properties=a.properties.toJSON()}return b};g.prototype.toJSON=function(){return this.c().map(function(a){a instanceof Element&&(a=r(a));return a})};i.prototype.toJSON=function(){for(var a={},b=this.names,c=-1,e;e=b[++c];)this[e]instanceof g&&(a[e]=this[e].toJSON());return a};_similar_Object_defineProperties_=function(a,b){var c,e;for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(c=b[e],"get"in c&&(a["get"+
e]=c.get),"set"in c&&(a["set"+e]=c.set))};_similar_Object_defineProperties_(j.Element.prototype,{itemValue:{get:function(){var a=this.nodeName;return this.getAttribute("itemscope")!==d?this:this.getAttribute("itemprop")===d?d:a in n?this.value:"META"===a?this.content:a in p?this.src:a in q?this.href:"OBJECT"===a?this.data:"TIME"===a&&this.getAttribute("datetime")?this.dateTime:"textContent"in this?this.textContent:this.innerText},set:function(a){var b=this.nodeName;if(this.getAttribute("itemprop")===
d)throw a=Object.create(DOMException.prototype),a.code=DOMException.INVALID_ACCESS_ERR,a.message="INVALID_ACCESS_ERR: DOM Exception "+a.code,a;return this[b in n?"value":"META"===b?"content":b in p?"src":b in q?"href":"OBJECT"===b?"data":"TIME"===b&&this.getAttribute("datetime")?"dateTime":"innerHTML"]=a}},itemProp:{get:function(){return l(this,"itemprop")},set:function(a){return this.setAttribute("itemprop",a+"",1),a}},itemScope:{get:function(){return this.getAttribute("itemscope",1)!==d},set:function(a){a?
this.setAttribute("itemscope","",1):this.removeAttribute("itemscope");return a}},itemId:{get:function(){var a=(this.getAttribute("itemid")||"").trim();a&&!/\w+:(\/\/)?[\w][\w.\/]*/.test(a)&&(a=location.href.replace(/\/[^\/]*$/,"/"+escape(a)));return a},set:function(a){return this.setAttribute("itemid",a+""),a}},itemType:{get:function(){return l(this,"itemtype")},set:function(a){return this.setAttribute("itemtype",a+""),a}},itemRef:{get:function(){return l(this,"itemref")},set:function(a){return this.setAttribute("itemref",
a+""),a}},properties:{get:function(){this._||(this._={});var a=this._._mcrdt_||(this._._mcrdt_={}),b=a.b;if(b)if(j.microdata_liveProperties)b.a();else return b;else b=a.b=new i;for(var c=[],a=[],e=[],h,f=-1,g;g=this.childNodes[++f];)1===g.nodeType&&c.push(g);this.getAttribute("itemref")&&(e=this.getAttribute("itemref").trim().split(/\s+/),e.forEach(function(a){(a=document.getElementById(a))&&c.push(a)}));c=c.filter(function(a,b){var g=d,f=a,h=[];if(c.indexOf(a)!==b&&-1!==c.indexOf(a,b))return!1;if(a.id&&
-1!==e.indexOf(a.id))return!0;for(;(f=f.parentNode)!==d&&1===f.nodeType;)if(h.push(f),f.getAttribute("itemscope")!==d){g=f;break}return g!==d?-1!==c.indexOf(g)?!1:!h.some(function(a){var b=-1,e=d;if(-1!==(b=c.indexOf(a))){for(a=c[b];(a=a.parentNode)!==d&&1===a.nodeType;)if(a.getAttribute("itemscope")!==d){e=a;break}if(e===g)return!0}return!1}):!0});for(c.sort(function(a,b){return 3-(b.compareDocumentPosition(a)&6)});h=c.pop();)if(h.getAttribute("itemprop")&&a.push(h),h.getAttribute("itemscope")===
d)for(f=h.childNodes.length;g=h.childNodes[--f];)1===g.nodeType&&c.push(g);a.forEach(b._push.bind(b));return b}}});f.getItems=document.getItems=function(a){return this.querySelectorAll(a?a.trim().split(/\s+/).map(function(a){return"[itemscope][itemtype~='"+a+"']"}).join(","):"")};j.PropertyNodeList||(j.PropertyNodeList=g);j.HTMLPropertiesCollection||(j.HTMLPropertiesCollection=i)}})(window);
}(window);
